package fair

import (
	"bytes"
	"testing"
)

// Test vectors generated by an independent reference implementation of the
// documented stream rule (see the repo's verification tooling). Fixed seed
// triples must reproduce these exact uint32 values; any divergence breaks
// client-side verification.
var knownVectors = []struct {
	serverSeed string
	clientSeed string
	nonce      int64
	want       []uint32
}{
	{
		serverSeed: "4f0c2ba1e6d54b8fa3c9d0e7f1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4",
		clientSeed: "player-one",
		nonce:      0,
		want: []uint32{
			1400997140, 1879464443, 3623590895, 304552459, // 0.3262 0.4376 0.8437 0.0709
			2266485560, 1317961764, 265180071, 1464178311, // 0.5277 0.3069 0.0617 0.3409
			759784894, 3268015235, 3404342710, 178170390, // 0.1769 0.7609 0.7926 0.0415
		},
	},
	{
		serverSeed: "4f0c2ba1e6d54b8fa3c9d0e7f1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4",
		clientSeed: "player-one",
		nonce:      1,
		want: []uint32{
			2361535121, 813668414, 3447456494, 1448813037,
			467956714, 2990109508, 4142463179, 783326819,
			3653864492, 2501788895, 740043026, 2074955236,
		},
	},
	{
		serverSeed: "4f0c2ba1e6d54b8fa3c9d0e7f1a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4",
		clientSeed: "other-client-seed",
		nonce:      0,
		want: []uint32{
			505172853, 2573725067, 4037141220, 3533030672,
			3074271341, 2141142167, 1601588295, 3420558495,
			4256017851, 1034634167, 4197898323, 368951851,
		},
	},
	{
		serverSeed: "ffeeddccbbaa99887766554433221100ffeeddccbbaa99887766554433221100",
		clientSeed: "",
		nonce:      7,
		want: []uint32{
			3754424, 1181092529, 656316314, 4245659917,
			4221362098, 4155269215, 445519844, 1950499706,
			1713107540, 1653527018, 2937198064, 1320176334,
		},
	},
}

// TestKnownOutcomes is the phase 3 gate: a table test reproducing known
// outcomes from fixed seed triples. 12 values = 48 bytes = spans three HMAC
// blocks, exercising the documented extension rule.
func TestKnownOutcomes(t *testing.T) {
	for _, tc := range knownVectors {
		s := NewPersonalStream([]byte(tc.serverSeed), tc.clientSeed, tc.nonce)
		for i, want := range tc.want {
			got := s.Uint32()
			if got != want {
				t.Fatalf("serverSeed=%q clientSeed=%q nonce=%d value %d: got %d want %d",
					tc.serverSeed, tc.clientSeed, tc.nonce, i, got, want)
			}
		}
	}
}

func TestFloatRangeAndDeterminism(t *testing.T) {
	s := NewPersonalStream([]byte("seed-a"), "client", 42)
	first := s.Float()
	if first < 0 || first >= 1 {
		t.Fatalf("float out of [0,1): %v", first)
	}
	for i := 0; i < 1000; i++ {
		if f := s.Float(); f < 0 || f >= 1 {
			t.Fatalf("float out of [0,1): %v", f)
		}
	}
	again := NewPersonalStream([]byte("seed-a"), "client", 42)
	if again.Float() != first {
		t.Fatal("same triple produced different values")
	}
	other := NewPersonalStream([]byte("seed-a"), "client", 43)
	if other.Float() == first {
		t.Fatal("different nonce produced same value")
	}
}

func TestChainStreamDeterministicAndSalted(t *testing.T) {
	chainSeed := bytes.Repeat([]byte{0xAB}, 32)
	a := NewChainStream(chainSeed, "salt-from-participant-client-seeds")
	b := NewChainStream(chainSeed, "salt-from-participant-client-seeds")

	for i := 0; i < 16; i++ {
		if a.Float() != b.Float() {
			t.Fatal("chain stream not deterministic for identical inputs")
		}
	}
	a2 := NewChainStream(chainSeed, "salt-from-participant-client-seeds")
	c2 := NewChainStream(chainSeed, "different-round-salt")
	if a2.Float() == c2.Float() {
		t.Fatal("different salts produced identical first values")
	}
}

func TestWeightedPick(t *testing.T) {
	weights := []int64{22, 20, 16, 14, 11, 8, 6, 3}
	s := NewPersonalStream([]byte("weighted-seed"), "client", 0)

	counts := make([]int, len(weights))
	for i := 0; i < 100000; i++ {
		counts[s.WeightedPick(weights)]++
	}
	for i, c := range counts {
		if c == 0 {
			t.Fatalf("index %d never selected", i)
		}
	}
	// Heavier symbols must be picked more often than lighter ones.
	if counts[0] <= counts[len(weights)-1] {
		t.Fatalf("heaviest weight (%d) not dominating lightest (%d)", counts[0], counts[len(weights)-1])
	}

	// Exact boundary: a float of exactly 0 targets the first index. Determined
	// by construction, not the RNG — build a stream and check the invariant
	// with a fixed set of draws instead.
	s2 := NewPersonalStream([]byte("boundary-seed"), "c", 0)
	for i := 0; i < 100; i++ {
		if idx := s2.WeightedPick([]int64{1}); idx != 0 {
			t.Fatalf("single-weight table returned index %d", idx)
		}
	}
}

func TestGenerateSeedAndHash(t *testing.T) {
	a, err := GenerateSeed()
	if err != nil {
		t.Fatal(err)
	}
	b, err := GenerateSeed()
	if err != nil {
		t.Fatal(err)
	}
	if len(a) != SeedSize || len(b) != SeedSize {
		t.Fatalf("seed length: %d %d", len(a), len(b))
	}
	if bytes.Equal(a, b) {
		t.Fatal("two generated seeds identical")
	}

	h1, h2 := HashSeed(a), HashSeed(a)
	if h1 != h2 || len(h1) != 64 {
		t.Fatalf("hash wrong: %q %q", h1, h2)
	}
	h3 := HashSeed(b)
	if h3 == h1 {
		t.Fatal("different seeds hashed identically")
	}
}
