/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness plus database reachability */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/guest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a guest session
         * @description Creates a guest user with 1000 credits, a wallet, and a server seed. Sets the session cookie.
         */
        post: operations["createGuest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/keycloak/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Establish the app identity from a Keycloak access token
         * @description Called by the BFF after an OIDC authorization-code exchange. Verifies the access token against the realm JWKS, provisions the local user on first login, and upgrades any guest session cookie in place — the same user row (wallet, bets, seeds) is retained and the guest session is revoked.
         */
        post: operations["keycloakSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current guest session and clear its cookie
         * @description Registered users authenticate via Keycloak and log out through the realm's end-session endpoint at the BFF; this endpoint only owns guest sessions.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active sessions for this user */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one session */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin OAuth flow */
        get: operations["oauthStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth callback */
        get: operations["oauthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user, wallet balance, and role
         * @description Resolves a Keycloak Bearer token (Authorization header) first, then the guest session cookie.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Game registry with paytables and RTP
         * @description Display only. Paytables and RTP live in Go; the client never computes payouts.
         */
        get: operations["listGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{id}/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Place a bet and receive the outcome
         * @description Server-authoritative. Runs the engine, debits/credits the wallet, and
         *     records the bet inside one transaction that takes the wallet row
         *     FOR UPDATE. Returns the outcome, the new balance, and the fairness
         *     triple used.
         *
         *     Idempotency: replaying the same idempotencyKey with an identical body
         *     returns the original result with no second transaction. The same key
         *     with a differing body returns 409.
         */
        post: operations["play"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated bet history, own bets only
         * @description Ownership is enforced in SQL (`WHERE user_id = $session_user`), never filtered in a handler.
         */
        get: operations["listBets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fair/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active server seed hash, client seed, and next nonce */
        get: operations["getFairCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fair/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate seeds
         * @description Reveals the old server seed and issues a new one with its hash published.
         */
        post: operations["rotateFair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Authenticated WebSocket (same session/Bearer auth as HTTP)
         * @description Client messages: subscribe_lobby, unsubscribe_lobby, join_room {slug},
         *     leave_room. Server messages: lobby_summary (1Hz), room_snapshot (on
         *     join and reconnect), session_revoked, error. place_bet and cash_out
         *     arrive with the round games.
         */
        get: operations["connectSocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User's saved themes */
        get: operations["listThemes"];
        put?: never;
        /**
         * Generate a theme from a prompt
         * @description Calls OpenRouter server-side. The response is validated before it is stored or applied; on any failure the current theme remains. Rate limited per user.
         */
        post: operations["createTheme"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lobby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rooms with live summaries */
        get: operations["getLobby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Room detail and current round snapshot
         * @description Standalone fetchable so deep links to /rooms/{slug} work without visiting the lobby.
         */
        get: operations["getRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ban or unban a user (moderator+)
         * @description Writes to audit_log. Banned users can read but cannot bet; their open sockets are closed.
         */
        post: operations["adminBan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjust a balance (admin only)
         * @description Writes an ordinary ledger transaction with kind admin_adjust and the actor recorded. Nothing writes wallets.balance_credits without a matching transaction row.
         */
        post: operations["adminAdjust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log (admin only) */
        get: operations["adminAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        User: {
            /** Format: int64 */
            id: number;
            displayName: string;
            isGuest: boolean;
            email?: string | null;
            emailVerified?: boolean;
            /** @enum {string} */
            role: "player" | "moderator" | "admin";
            /** @enum {string} */
            status: "active" | "banned" | "self_excluded";
            /** Format: date-time */
            createdAt: string;
        };
        Me: {
            user: components["schemas"]["User"];
            /** Format: int64 */
            balanceCredits: number;
        };
        SessionInfo: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            expiresAt: string;
            ip?: string | null;
            userAgent?: string | null;
        };
        Room: {
            /** Format: int64 */
            id: number;
            slug: string;
            name: string;
            gameId: string;
            /** Format: int64 */
            minBet: number;
            /** Format: int64 */
            maxBet: number;
            capacity: number;
            playerCount: number;
        };
        Game: {
            id: string;
            name: string;
            theoreticalRtp: number;
            /** @description Game-specific display data (symbol weights/pays for slots) */
            paytable?: unknown;
        };
        PlayRequest: {
            /**
             * Format: int64
             * @description One of the server-enforced bet steps (5/10/25/50/100 for slots)
             */
            betCredits: number;
            clientSeed: string;
            idempotencyKey: string;
        };
        PlayResponse: {
            /** Format: int64 */
            betId: number;
            /** Format: int64 */
            payoutCredits: number;
            /** Format: int64 */
            balanceCredits: number;
            /** @description Game-specific payload rendered by the client (3x3 grid + winning lines for slots) */
            outcome: unknown;
            fairness: components["schemas"]["FairnessTriple"];
        };
        FairnessTriple: {
            serverSeedHash: string;
            clientSeed: string;
            /** Format: int64 */
            nonce: number;
        };
        FairCurrent: {
            serverSeedHash: string;
            clientSeed: string;
            /** Format: int64 */
            nonce: number;
        };
        Bet: {
            /** Format: int64 */
            id: number;
            gameId: string;
            /** Format: int64 */
            roundId?: number;
            /** Format: int64 */
            betCredits: number;
            /** Format: int64 */
            payoutCredits: number;
            /** Format: int64 */
            nonce: number;
            clientSeed: string;
            serverSeedHash: string;
            outcome?: unknown;
            /** Format: date-time */
            createdAt: string;
        };
        Theme: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @description Exactly 8 hex colors; index 0 is transparent */
            palette: string[];
            /** @description Exactly 8 sprites, each 16 rows of 16 hex-digit characters */
            sprites: {
                name: string;
                rows: string[];
            }[];
            /** Format: date-time */
            createdAt: string;
        };
        LobbySummary: {
            slug: string;
            gameId: string;
            name: string;
            playerCount: number;
            /** @enum {string} */
            roundState: "betting_open" | "locked" | "running" | "settled";
            /** @description Coarsely rounded; meaningful for curve games only */
            multiplier?: number | null;
            /** @description Last few results as pixel-chip data */
            recentResults?: number[];
        };
        RoomSnapshot: {
            slug: string;
            gameId: string;
            name: string;
            /** Format: int64 */
            minBet: number;
            /** Format: int64 */
            maxBet: number;
            capacity: number;
            /** @enum {string} */
            roundState: "betting_open" | "locked" | "running" | "settled";
            multiplier?: number | null;
            playerCount: number;
        };
        AuditEntry: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            actorUserId?: number | null;
            action: string;
            targetType?: string | null;
            /** Format: int64 */
            targetId?: number | null;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy; migrated database answered a query */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        database?: string;
                    };
                };
            };
            503: components["responses"]["Error"];
        };
    };
    createGuest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Guest created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            429: components["responses"]["Error"];
        };
    };
    keycloakSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    accessToken: string;
                };
            };
        };
        responses: {
            /** @description Identity established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    oauthStart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "discord" | "google";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to provider */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauthCallback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "discord" | "google";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect into the app with a session set */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered games */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"][];
                };
            };
        };
    };
    play: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayRequest"];
            };
        };
        responses: {
            /** @description Outcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayResponse"];
                };
            };
            400: components["responses"]["Error"];
            402: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    listBets: {
        parameters: {
            query?: {
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bet page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        bets?: components["schemas"]["Bet"][];
                        nextCursor?: string | null;
                    };
                };
            };
        };
    };
    getFairCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fairness state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FairCurrent"];
                };
            };
        };
    };
    rotateFair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    clientSeed: string;
                };
            };
        };
        responses: {
            /** @description Old seed revealed, new seed active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revealedServerSeed: string;
                        serverSeedHash: string;
                        clientSeed: string;
                        /** Format: int64 */
                        nonce: number;
                    };
                };
            };
        };
    };
    connectSocket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    listThemes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Themes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Theme"][];
                };
            };
        };
    };
    createTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    prompt: string;
                };
            };
        };
        responses: {
            /** @description Generated theme */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Theme"];
                };
            };
            400: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    getLobby: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lobby */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rooms?: components["schemas"]["LobbySummary"][];
                    };
                };
            };
        };
    };
    getRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshot"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    adminBan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    banned: boolean;
                };
            };
        };
        responses: {
            /** @description Applied */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    adminAdjust: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: int64
                     * @description Signed; negative debits, positive credits
                     */
                    amountCredits: number;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description New balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        balanceCredits?: number;
                    };
                };
            };
            403: components["responses"]["Error"];
        };
    };
    adminAudit: {
        parameters: {
            query?: {
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries?: components["schemas"]["AuditEntry"][];
                        nextCursor?: string | null;
                    };
                };
            };
        };
    };
}
