/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness plus database reachability */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/guest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a guest session
         * @description Creates a guest user with 1000 credits, a wallet, and a server seed. Sets the session cookie.
         */
        post: operations["createGuest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/keycloak/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Establish the app identity from a Keycloak access token
         * @description Called by the BFF after an OIDC authorization-code exchange. Verifies the access token against the realm JWKS, provisions the local user on first login, and upgrades any guest session cookie in place — the same user row (wallet, bets, seeds) is retained and the guest session is revoked.
         */
        post: operations["keycloakSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current guest session and clear its cookie
         * @description Registered users authenticate via Keycloak and log out through the realm's end-session endpoint at the BFF; this endpoint only owns guest sessions.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active sessions for this user */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one session */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user, wallet balance, and role
         * @description Resolves a Keycloak Bearer token (Authorization header) first, then the guest session cookie.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit the caller's profile (display name, avatar preset)
         * @description Display names are 3-20 chars (letters, digits, spaces, _ and -), case-insensitively unique, and cooldown-limited to one change per 24h (the first rename is exempt). Guests may rename too; the Keycloak write-back only applies to registered accounts.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v1/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload an avatar (registered players only)
         * @description Body is raw PNG or JPEG bytes (max 1MB). The server center-crops, downscales to 64x64 pixels, and stores the result; subsequent renders use the bumped avatarVersion to cache-bust.
         */
        put: operations["uploadAvatar"];
        post?: never;
        /** Clear the caller's avatar (preset and upload) */
        delete: operations["deleteAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/self-exclude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Self-exclude from betting */
        post: operations["selfExclude"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim the hourly play-money top-up */
        post: operations["deposit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve a player's uploaded avatar image
         * @description 404 unless the player uploaded an image and has no preset selected. Responses are immutable; the version query cache-busts.
         */
        get: operations["getUserAvatar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public profile slice for a player */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Game registry with paytables and RTP
         * @description Display only. Paytables and RTP live in Go; the client never computes payouts.
         */
        get: operations["listGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{id}/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Place a bet and receive the outcome
         * @description Server-authoritative. Runs the engine, debits/credits the wallet, and
         *     records the bet inside one transaction that takes the wallet row
         *     FOR UPDATE. Returns the outcome, the new balance, and the fairness
         *     triple used.
         *
         *     Idempotency: replaying the same idempotencyKey with an identical body
         *     returns the original result with no second transaction. The same key
         *     with a differing body returns 409.
         */
        post: operations["play"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/blackjack/deal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deal a blackjack hand
         * @description Server-authoritative, stateful. Shuffles a full deck from the personal
         *     fair stream (HMAC Fisher-Yates), deals two cards each, debits the
         *     stake, and records the bet + hand in one transaction. A natural 21
         *     (player or dealer) resolves and pays inside the same transaction.
         *     While the hand is active the dealer's hole card is withheld.
         *
         *     One active hand per user; an abandoned hand (idle > 5 min)
         *     auto-stands on the next deal. Idempotent like /play.
         */
        post: operations["blackjackDeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hands/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's in-progress blackjack hand, if any */
        get: operations["getActiveHand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hands/{id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hit, stand, or double the active hand
         * @description Replays the hand from the fairness triple + action log, applies the
         *     action, and persists in one transaction. Double debits the extra
         *     stake; stand / bust / 21 completes the hand: the dealer plays out and
         *     the payout credits atomically. Retried idempotency keys return the
         *     current state without drawing again.
         */
        post: operations["handAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated bet history, own bets only
         * @description Ownership is enforced in SQL (`WHERE user_id = $session_user`), never filtered in a handler.
         */
        get: operations["listBets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fair/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active server seed hash, client seed, and next nonce */
        get: operations["getFairCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fair/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate seeds
         * @description Reveals the old server seed and issues a new one with its hash published.
         */
        post: operations["rotateFair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Authenticated WebSocket (same session/Bearer auth as HTTP)
         * @description Client messages: subscribe_lobby, unsubscribe_lobby, join_room {slug},
         *     leave_room. Server messages: lobby_summary (1Hz), room_snapshot (on
         *     join and reconnect), session_revoked, error. place_bet and cash_out
         *     arrive with the round games.
         */
        get: operations["connectSocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User's saved themes */
        get: operations["listThemes"];
        put?: never;
        /**
         * Generate a theme from a prompt
         * @description Calls OpenRouter server-side. The response is validated before it is stored or applied; on any failure the current theme remains. Rate limited per user.
         */
        post: operations["createTheme"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lobby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rooms with live summaries */
        get: operations["getLobby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Room detail and current round snapshot
         * @description Standalone fetchable so deep links to /rooms/{slug} work without visiting the lobby.
         */
        get: operations["getRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lobby/personalized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's personalized lobby payload
         * @description Deterministic per-player ranking over the game catalog, plus curated
         *     sections. Responsible-gambling gates run first: a suppressed or
         *     restricted player keeps neutral navigation but every promotional
         *     surface (forYou, trending, new, promo badges) drops out. Cached
         *     server-side for ~30s.
         */
        get: operations["personalizedLobby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fire-and-forget behavioral events
         * @description Lightweight launch tracking (a game or table page was opened). Works
         *     for guests; powers trending and cold-start "continue". Best-effort:
         *     invalid rows are dropped, never fatal.
         */
        post: operations["playerEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update player preferences
         * @description Currently the lobby-personalization toggle (transparency / DSA-style
         *     non-profiling option). Turning it off restores the static lobby for
         *     this player. Audited like other profile mutations.
         */
        patch: operations["updatePreferences"];
        trace?: never;
    };
    "/api/v1/shop/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active vault catalog */
        get: operations["getShopItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shop/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's owned shop items */
        get: operations["getShopInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shop/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Buy one catalog item with credits
         * @description One wallet transaction: ledger debit (kind shop_purchase) plus the
         *     inventory grant, idempotency-keyed like a bet. A replayed key returns
         *     the original result; an already-owned item is never charged twice.
         */
        post: operations["purchaseShopItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/cosmetics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Equip or clear cosmetic slots
         * @description Free, but every slot is validated against the catalog (kind match and
         *     ownership). Republishes the profile event so other players see the
         *     change live.
         */
        patch: operations["updateCosmetics"];
        trace?: never;
    };
    "/api/v1/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Newest chat lines for dock mounting */
        get: operations["getChatHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top-20 aggregate plus the caller's own rank */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List or search users (moderator+) */
        get: operations["adminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ban or unban a user (moderator+)
         * @description Writes to audit_log. Banned users can read but cannot bet; their open sockets are closed.
         */
        post: operations["adminBan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjust a balance (admin only)
         * @description Writes an ordinary ledger transaction with kind admin_adjust and the actor recorded. Nothing writes wallets.balance_credits without a matching transaction row.
         */
        post: operations["adminAdjust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log (admin only) */
        get: operations["adminAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        User: {
            /** Format: int64 */
            id: number;
            displayName: string;
            isGuest: boolean;
            email?: string | null;
            emailVerified?: boolean;
            /** @enum {string} */
            role: "player" | "moderator" | "admin";
            /** @enum {string} */
            status: "active" | "banned" | "self_excluded";
            /** Format: date-time */
            createdAt: string;
            /** @description Curated avatar sprite key; empty = none (an upload may exist) */
            avatarPreset?: string;
            /**
             * Format: int64
             * @description Bumped on every avatar change; > 0 with empty preset = upload
             */
            avatarVersion?: number;
            /** @description Equipped shop title item id; empty = none */
            title?: string;
            /** @description Equipped shop name-effect item id; empty = none */
            nameEffect?: string;
            /** @description Equipped shop card-skin item id; empty = classic */
            cardSkin?: string;
            /** @description Equipped shop avatar-frame item id; empty = none */
            avatarFrame?: string;
            /** @description Equipped shop plinko-ball item id; empty = classic */
            plinkoBall?: string;
            /** @description Equipped shop profile-theme item id; empty = default */
            profileTheme?: string;
        };
        Me: {
            user: components["schemas"]["User"];
            /** Format: int64 */
            balanceCredits: number;
        };
        ProfileUpdateRequest: {
            displayName?: string;
            /** @description Preset sprite key; empty string clears the preset */
            avatarPreset?: string;
        };
        AvatarUploadResponse: {
            /** Format: int64 */
            avatarVersion: number;
        };
        PublicProfile: {
            /** Format: int64 */
            id: number;
            displayName: string;
            avatarPreset: string;
            /** Format: int64 */
            avatarVersion: number;
            role: string;
            /** Format: date-time */
            createdAt: string;
            title?: string;
            nameEffect?: string;
            cardSkin?: string;
            avatarFrame?: string;
            plinkoBall?: string;
            profileTheme?: string;
        };
        ChatMessage: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            userId: number;
            displayName: string;
            avatarPreset: string;
            /** Format: int64 */
            avatarVersion: number;
            role: string;
            title?: string;
            nameEffect?: string;
            /** @enum {string} */
            kind: "chat" | "system";
            body: string;
            /** Format: date-time */
            createdAt: string;
        };
        ChatHistory: {
            messages: components["schemas"]["ChatMessage"][];
        };
        LeaderboardEntry: {
            rank: number;
            /** Format: int64 */
            userId: number;
            displayName: string;
            avatarPreset?: string;
            /** Format: int64 */
            avatarVersion?: number;
            title?: string;
            nameEffect?: string;
            /** Format: int64 */
            value: number;
        };
        Leaderboard: {
            /** @enum {string} */
            metric: "biggest_win" | "net_profit" | "wagered";
            /** @enum {string} */
            window: "daily" | "weekly" | "all";
            entries: components["schemas"]["LeaderboardEntry"][];
            me?: components["schemas"]["LeaderboardEntry"] | null;
        };
        ShopItem: {
            id: string;
            /** @enum {string} */
            kind: "title" | "name_effect" | "card_skin" | "avatar_frame" | "plinko_ball" | "profile_theme" | "emote_pack";
            name: string;
            blurb?: string;
            /** Format: int64 */
            priceCredits: number;
            /** @enum {string} */
            rarity: "common" | "rare" | "epic" | "legendary";
            /** @description Kind-specific extras; emote packs list their emote ids here */
            payload?: {
                emotes?: string[];
            };
        };
        ShopCatalog: {
            items: components["schemas"]["ShopItem"][];
        };
        ShopInventory: {
            items: {
                itemId: string;
                /** Format: date-time */
                acquiredAt: string;
            }[];
        };
        ShopPurchaseRequest: {
            itemId: string;
            idempotencyKey: string;
        };
        ShopPurchaseResponse: {
            itemId: string;
            /** Format: int64 */
            balanceCredits: number;
            replay?: boolean;
            alreadyOwned?: boolean;
        };
        /** @description Equip (item id) or clear (empty string) cosmetic slots; omitted slots stay untouched */
        CosmeticsUpdate: {
            title?: string;
            nameEffect?: string;
            cardSkin?: string;
            avatarFrame?: string;
            plinkoBall?: string;
            profileTheme?: string;
        };
        AdminUserRow: {
            /** Format: int64 */
            id: number;
            displayName: string;
            isGuest: boolean;
            email?: string | null;
            emailVerified?: boolean;
            role: string;
            /** @enum {string} */
            status: "active" | "banned" | "self_excluded";
            /** Format: date-time */
            statusUntil?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AdminUserList: {
            users: components["schemas"]["AdminUserRow"][];
        };
        SessionInfo: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            expiresAt: string;
            ip?: string | null;
            userAgent?: string | null;
        };
        Room: {
            /** Format: int64 */
            id: number;
            slug: string;
            name: string;
            gameId: string;
            /** Format: int64 */
            minBet: number;
            /** Format: int64 */
            maxBet: number;
            capacity: number;
            playerCount: number;
        };
        Game: {
            id: string;
            name: string;
            theoreticalRtp: number;
            /**
             * @description instant = single-call engines; stateful = deal/action flow (blackjack)
             * @enum {string}
             */
            kind?: "instant" | "stateful";
            betSteps?: number[];
            /** @description Game-specific display data (symbol weights/pays for slots) */
            paytable?: unknown;
            /**
             * @description Catalog grouping used by the lobby tree
             * @enum {string}
             */
            category?: "slots" | "instant" | "table" | "live";
            /** @description Family label (classic, fruit, adventure, originals) */
            collection?: string;
            /** @description Free-form affinity tags powering "because you played" neighbours */
            tags?: string[];
            isNew?: boolean;
            blurb?: string;
        };
        PersonalizedEntry: {
            gameId: string;
            /** @description Honest small-print reason ("2H AGO", "BECAUSE YOU PLAYED FRUITS") */
            label?: string;
        };
        PersonalizedLobby: {
            personalized: boolean;
            promoEligible: boolean;
            /**
             * @description Why the flags are set; empty when fully personalized
             * @enum {string}
             */
            reason?: "account_restricted" | "toggle_off" | "cold" | "risk_suppressed";
            /** @description All catalog game ids, best first */
            gameRank: string[];
            continue: components["schemas"]["PersonalizedEntry"][];
            forYou: components["schemas"]["PersonalizedEntry"][];
            trending: string[];
            new: string[];
            badges: {
                [key: string]: "TOP PICK" | "HOT" | "NEW" | "RECENT";
            };
        };
        EventsRequest: {
            events: {
                /** @enum {string} */
                type: "launch";
                gameId: string;
                context?: {
                    [key: string]: unknown;
                };
            }[];
        };
        EventsAccepted: {
            accepted: number;
        };
        PreferencesUpdate: {
            personalizeEnabled: boolean;
        };
        Preferences: {
            personalizeEnabled: boolean;
        };
        PlayRequest: {
            /**
             * Format: int64
             * @description One of the server-enforced bet steps (5/10/25/50/100 for slots)
             */
            betCredits: number;
            clientSeed: string;
            idempotencyKey: string;
        };
        PlayResponse: {
            /** Format: int64 */
            betId: number;
            /** Format: int64 */
            payoutCredits: number;
            /** Format: int64 */
            balanceCredits: number;
            /** @description Game-specific payload rendered by the client (3x3 grid + winning lines for slots) */
            outcome: unknown;
            fairness: components["schemas"]["FairnessTriple"];
        };
        FairnessTriple: {
            serverSeedHash: string;
            clientSeed: string;
            /** Format: int64 */
            nonce: number;
        };
        BlackjackDealRequest: {
            /**
             * Format: int64
             * @description One of the game's bet steps
             */
            betCredits: number;
            clientSeed?: string;
            idempotencyKey: string;
        };
        BlackjackHand: {
            /** Format: int64 */
            handId: number;
            /** Format: int64 */
            betId: number;
            /** @enum {string} */
            status: "active" | "complete";
            /** Format: int64 */
            betCredits: number;
            /** Format: int64 */
            payoutCredits: number;
            /**
             * @description Present once the hand is complete
             * @enum {string}
             */
            outcome?: "blackjack" | "win" | "push" | "lose" | "bust";
            /** @description Compact card codes, e.g. "AsKd7c" */
            playerCards: string;
            /** @description Up card only while the hand is active; full hand once complete */
            dealerCards: string;
            playerTotal: number;
            /** @description Present once the hand is complete */
            dealerTotal?: number | null;
            doubled: boolean;
            canDouble: boolean;
            actions: ("hit" | "stand" | "double")[];
        };
        HandResponse: {
            hand: components["schemas"]["BlackjackHand"];
            /** Format: int64 */
            balanceCredits: number;
            fairness: components["schemas"]["FairnessTriple"];
            replay: boolean;
        };
        FairCurrent: {
            serverSeedHash: string;
            clientSeed: string;
            /** Format: int64 */
            nonce: number;
        };
        Bet: {
            /** Format: int64 */
            id: number;
            gameId: string;
            /** Format: int64 */
            roundId?: number;
            /** Format: int64 */
            betCredits: number;
            /** Format: int64 */
            payoutCredits: number;
            /** Format: int64 */
            nonce: number;
            clientSeed: string;
            serverSeedHash: string;
            outcome?: unknown;
            /** Format: date-time */
            createdAt: string;
        };
        Theme: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @description Exactly 8 hex colors; index 0 is transparent */
            palette: string[];
            /** @description Exactly 8 sprites, each 16 rows of 16 hex-digit characters */
            sprites: {
                name: string;
                rows: string[];
            }[];
            /** Format: date-time */
            createdAt: string;
        };
        LobbySummary: {
            slug: string;
            gameId: string;
            name: string;
            playerCount: number;
            /** @enum {string} */
            roundState: "betting_open" | "locked" | "running" | "settled";
            /** @description Coarsely rounded; meaningful for curve games only */
            multiplier?: number | null;
            /** @description Last few results as pixel-chip data */
            recentResults?: number[];
        };
        RoomSnapshot: {
            slug: string;
            gameId: string;
            name: string;
            /** Format: int64 */
            minBet: number;
            /** Format: int64 */
            maxBet: number;
            capacity: number;
            /** @enum {string} */
            roundState: "betting_open" | "locked" | "running" | "settled";
            multiplier?: number | null;
            playerCount: number;
        };
        AuditEntry: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            actorUserId?: number | null;
            action: string;
            targetType?: string | null;
            /** Format: int64 */
            targetId?: number | null;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy; migrated database answered a query */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        database?: string;
                    };
                };
            };
            503: components["responses"]["Error"];
        };
    };
    createGuest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Guest created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            429: components["responses"]["Error"];
        };
    };
    keycloakSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    accessToken: string;
                };
            };
        };
        responses: {
            /** @description Identity established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated identity and balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            /** @description Rename cooldown active */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Display name already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/png": string;
                "image/jpeg": string;
            };
        };
        responses: {
            /** @description New avatar version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarUploadResponse"];
                };
            };
            401: components["responses"]["Error"];
            /** @description Guests cannot upload */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            415: components["responses"]["Error"];
        };
    };
    deleteAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    selfExclude: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    days?: number | null;
                };
            };
        };
        responses: {
            /** @description New status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        /** Format: date-time */
                        statusUntil?: string | null;
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    deposit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deposit result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        balanceCredits?: number;
                        claimed?: boolean;
                        /** Format: int64 */
                        amountCredits?: number;
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getUserAvatar: {
        parameters: {
            query?: {
                v?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avatar image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered games */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"][];
                };
            };
        };
    };
    play: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayRequest"];
            };
        };
        responses: {
            /** @description Outcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayResponse"];
                };
            };
            400: components["responses"]["Error"];
            402: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    blackjackDeal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlackjackDealRequest"];
            };
        };
        responses: {
            /** @description Hand state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandResponse"];
                };
            };
            400: components["responses"]["Error"];
            402: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    getActiveHand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active hand or null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        hand?: components["schemas"]["BlackjackHand"] | null;
                    };
                };
            };
        };
    };
    handAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    action: "hit" | "stand" | "double";
                    idempotencyKey: string;
                };
            };
        };
        responses: {
            /** @description Hand state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandResponse"];
                };
            };
            400: components["responses"]["Error"];
            402: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    listBets: {
        parameters: {
            query?: {
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bet page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        bets?: components["schemas"]["Bet"][];
                        nextCursor?: string | null;
                    };
                };
            };
        };
    };
    getFairCurrent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fairness state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FairCurrent"];
                };
            };
        };
    };
    rotateFair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    clientSeed: string;
                };
            };
        };
        responses: {
            /** @description Old seed revealed, new seed active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revealedServerSeed: string;
                        serverSeedHash: string;
                        clientSeed: string;
                        /** Format: int64 */
                        nonce: number;
                    };
                };
            };
        };
    };
    connectSocket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    listThemes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Themes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Theme"][];
                };
            };
        };
    };
    createTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    prompt: string;
                };
            };
        };
        responses: {
            /** @description Generated theme */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Theme"];
                };
            };
            400: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    getLobby: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lobby */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rooms?: components["schemas"]["LobbySummary"][];
                    };
                };
            };
        };
    };
    getRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshot"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    personalizedLobby: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked games and sections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalizedLobby"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    playerEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventsRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsAccepted"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description New preference value */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    getShopItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog items ordered by kind and price */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopCatalog"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getShopInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owned items, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopInventory"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    purchaseShopItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShopPurchaseRequest"];
            };
        };
        responses: {
            /** @description Purchase recorded (or replayed / already owned) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopPurchaseResponse"];
                };
            };
            401: components["responses"]["Error"];
            402: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    updateCosmetics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CosmeticsUpdate"];
            };
        };
        responses: {
            /** @description Updated me payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getChatHistory: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat history, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistory"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getLeaderboard: {
        parameters: {
            query?: {
                metric?: "biggest_win" | "net_profit" | "wagered";
                window?: "daily" | "weekly" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard entries (top 20) and the caller's rank when present */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                /** @description Substring match on display name or email; empty lists newest first */
                query?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserList"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminBan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    banned: boolean;
                };
            };
        };
        responses: {
            /** @description Applied */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    adminAdjust: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: int64
                     * @description Signed; negative debits, positive credits
                     */
                    amountCredits: number;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description New balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        balanceCredits?: number;
                    };
                };
            };
            403: components["responses"]["Error"];
        };
    };
    adminAudit: {
        parameters: {
            query?: {
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries?: components["schemas"]["AuditEntry"][];
                        nextCursor?: string | null;
                    };
                };
            };
        };
    };
}
