// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserStatus = `-- name: GetUserStatus :one
SELECT status FROM users WHERE id = $1
`

func (q *Queries) GetUserStatus(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getUserStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const insertAuditEntry = `-- name: InsertAuditEntry :one
INSERT INTO audit_log (actor_user_id, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertAuditEntryParams struct {
	ActorUserID pgtype.Int8
	Action      string
	TargetType  pgtype.Text
	TargetID    pgtype.Int8
	Metadata    []byte
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAuditEntry,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT id, actor_user_id, action, target_type, target_id, metadata, created_at
FROM audit_log
WHERE ($1::bigint IS NULL OR id < $1)
ORDER BY id DESC
LIMIT $2
`

type ListAuditEntriesParams struct {
	Cursor pgtype.Int8
	Lim    int32
}

func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntries, arg.Cursor, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role = $2 WHERE id = $1
`

type SetUserRoleParams struct {
	ID   int64
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role)
	return err
}

const setUserStatus = `-- name: SetUserStatus :exec
UPDATE users
SET status = $2, status_until = $3
WHERE id = $1
`

type SetUserStatusParams struct {
	ID          int64
	Status      string
	StatusUntil *time.Time
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) error {
	_, err := q.db.Exec(ctx, setUserStatus, arg.ID, arg.Status, arg.StatusUntil)
	return err
}
