// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: avatars.sql

package store

import (
	"context"
)

const deleteUserAvatar = `-- name: DeleteUserAvatar :exec
DELETE FROM user_avatars WHERE user_id = $1
`

func (q *Queries) DeleteUserAvatar(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserAvatar, userID)
	return err
}

const getUserAvatar = `-- name: GetUserAvatar :one
SELECT content_type, bytes
FROM user_avatars
WHERE user_id = $1
`

type GetUserAvatarRow struct {
	ContentType string
	Bytes       []byte
}

func (q *Queries) GetUserAvatar(ctx context.Context, userID int64) (GetUserAvatarRow, error) {
	row := q.db.QueryRow(ctx, getUserAvatar, userID)
	var i GetUserAvatarRow
	err := row.Scan(&i.ContentType, &i.Bytes)
	return i, err
}

const upsertUserAvatar = `-- name: UpsertUserAvatar :exec
INSERT INTO user_avatars (user_id, content_type, bytes, sha256)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET content_type = EXCLUDED.content_type,
    bytes        = EXCLUDED.bytes,
    sha256       = EXCLUDED.sha256,
    updated_at   = now()
`

type UpsertUserAvatarParams struct {
	UserID      int64
	ContentType string
	Bytes       []byte
	Sha256      string
}

func (q *Queries) UpsertUserAvatar(ctx context.Context, arg UpsertUserAvatarParams) error {
	_, err := q.db.Exec(ctx, upsertUserAvatar,
		arg.UserID,
		arg.ContentType,
		arg.Bytes,
		arg.Sha256,
	)
	return err
}
