// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bets.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBetsForUser = `-- name: CountBetsForUser :one
SELECT COUNT(*)::bigint FROM bets WHERE user_id = $1
`

func (q *Queries) CountBetsForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBetsForUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSettledRound = `-- name: CreateSettledRound :one
INSERT INTO rounds (game_id, state, result, opened_at, locked_at, settled_at)
VALUES ($1, 'settled', $2, now(), now(), now())
RETURNING id
`

type CreateSettledRoundParams struct {
	GameID string
	Result []byte
}

// Single-player bets get a synthetic one-player round so bets.round_id is
// always non-null. Round games write real state transitions later.
func (q *Queries) CreateSettledRound(ctx context.Context, arg CreateSettledRoundParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSettledRound, arg.GameID, arg.Result)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getBetByID = `-- name: GetBetByID :one
SELECT id, user_id, game_id, round_id, bet_credits, payout_credits,
       server_seed_id, client_seed, nonce, outcome, created_at
FROM bets
WHERE id = $1
`

type GetBetByIDRow struct {
	ID            int64
	UserID        int64
	GameID        string
	RoundID       int64
	BetCredits    int64
	PayoutCredits int64
	ServerSeedID  pgtype.Int8
	ClientSeed    pgtype.Text
	Nonce         pgtype.Int8
	Outcome       []byte
	CreatedAt     time.Time
}

func (q *Queries) GetBetByID(ctx context.Context, id int64) (GetBetByIDRow, error) {
	row := q.db.QueryRow(ctx, getBetByID, id)
	var i GetBetByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.RoundID,
		&i.BetCredits,
		&i.PayoutCredits,
		&i.ServerSeedID,
		&i.ClientSeed,
		&i.Nonce,
		&i.Outcome,
		&i.CreatedAt,
	)
	return i, err
}

const insertBet = `-- name: InsertBet :one
INSERT INTO bets (user_id, game_id, round_id, bet_credits, payout_credits,
                  server_seed_id, client_seed, nonce, outcome)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at
`

type InsertBetParams struct {
	UserID        int64
	GameID        string
	RoundID       int64
	BetCredits    int64
	PayoutCredits int64
	ServerSeedID  pgtype.Int8
	ClientSeed    pgtype.Text
	Nonce         pgtype.Int8
	Outcome       []byte
}

type InsertBetRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) InsertBet(ctx context.Context, arg InsertBetParams) (InsertBetRow, error) {
	row := q.db.QueryRow(ctx, insertBet,
		arg.UserID,
		arg.GameID,
		arg.RoundID,
		arg.BetCredits,
		arg.PayoutCredits,
		arg.ServerSeedID,
		arg.ClientSeed,
		arg.Nonce,
		arg.Outcome,
	)
	var i InsertBetRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listBetsByUser = `-- name: ListBetsByUser :many
SELECT id, game_id, round_id, bet_credits, payout_credits,
       client_seed, nonce, outcome, created_at
FROM bets
WHERE user_id = $1
  AND ($2::bigint IS NULL OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListBetsByUserParams struct {
	UserID int64
	Cursor pgtype.Int8
	Lim    int32
}

type ListBetsByUserRow struct {
	ID            int64
	GameID        string
	RoundID       int64
	BetCredits    int64
	PayoutCredits int64
	ClientSeed    pgtype.Text
	Nonce         pgtype.Int8
	Outcome       []byte
	CreatedAt     time.Time
}

// Ownership enforced in the query, never filtered in a handler.
func (q *Queries) ListBetsByUser(ctx context.Context, arg ListBetsByUserParams) ([]ListBetsByUserRow, error) {
	rows, err := q.db.Query(ctx, listBetsByUser, arg.UserID, arg.Cursor, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBetsByUserRow
	for rows.Next() {
		var i ListBetsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.RoundID,
			&i.BetCredits,
			&i.PayoutCredits,
			&i.ClientSeed,
			&i.Nonce,
			&i.Outcome,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
