// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chain.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnrevealedChainSeeds = `-- name: CountUnrevealedChainSeeds :one
SELECT count(*)::bigint FROM chain_seeds WHERE revealed_at IS NULL
`

func (q *Queries) CountUnrevealedChainSeeds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnrevealedChainSeeds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getNextUnrevealedChainSeed = `-- name: GetNextUnrevealedChainSeed :one
SELECT id, chain_group, index, seed_hash, seed_plain
FROM chain_seeds
WHERE revealed_at IS NULL
ORDER BY index DESC
LIMIT 1
`

type GetNextUnrevealedChainSeedRow struct {
	ID         int64
	ChainGroup int64
	Index      int64
	SeedHash   string
	SeedPlain  pgtype.Text
}

// Rounds consume the chain in reverse: the next link is the highest
// unrevealed index.
func (q *Queries) GetNextUnrevealedChainSeed(ctx context.Context) (GetNextUnrevealedChainSeedRow, error) {
	row := q.db.QueryRow(ctx, getNextUnrevealedChainSeed)
	var i GetNextUnrevealedChainSeedRow
	err := row.Scan(
		&i.ID,
		&i.ChainGroup,
		&i.Index,
		&i.SeedHash,
		&i.SeedPlain,
	)
	return i, err
}

const getRevealedChainSeedAfter = `-- name: GetRevealedChainSeedAfter :one
SELECT id, chain_group, index, seed_hash, seed_plain
FROM chain_seeds
WHERE revealed_at IS NOT NULL AND index > $1 AND chain_group = $2
ORDER BY index ASC
LIMIT 1
`

type GetRevealedChainSeedAfterParams struct {
	Index      int64
	ChainGroup int64
}

type GetRevealedChainSeedAfterRow struct {
	ID         int64
	ChainGroup int64
	Index      int64
	SeedHash   string
	SeedPlain  pgtype.Text
}

// The previously revealed link within the same chain (consumption is
// strictly descending, so the predecessor of index N is the smallest
// revealed index > N in this group).
func (q *Queries) GetRevealedChainSeedAfter(ctx context.Context, arg GetRevealedChainSeedAfterParams) (GetRevealedChainSeedAfterRow, error) {
	row := q.db.QueryRow(ctx, getRevealedChainSeedAfter, arg.Index, arg.ChainGroup)
	var i GetRevealedChainSeedAfterRow
	err := row.Scan(
		&i.ID,
		&i.ChainGroup,
		&i.Index,
		&i.SeedHash,
		&i.SeedPlain,
	)
	return i, err
}

const insertChainSeed = `-- name: InsertChainSeed :exec
INSERT INTO chain_seeds (chain_group, index, seed_hash, seed_plain)
VALUES ($1, $2, $3, $4)
ON CONFLICT (index) DO NOTHING
`

type InsertChainSeedParams struct {
	ChainGroup int64
	Index      int64
	SeedHash   string
	SeedPlain  pgtype.Text
}

func (q *Queries) InsertChainSeed(ctx context.Context, arg InsertChainSeedParams) error {
	_, err := q.db.Exec(ctx, insertChainSeed,
		arg.ChainGroup,
		arg.Index,
		arg.SeedHash,
		arg.SeedPlain,
	)
	return err
}

const maxChainIndex = `-- name: MaxChainIndex :one
SELECT COALESCE(MAX(index), 0)::bigint FROM chain_seeds
`

func (q *Queries) MaxChainIndex(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, maxChainIndex)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextChainGroup = `-- name: NextChainGroup :one
SELECT (COALESCE(MAX(chain_group), 0)::bigint + 1)::bigint FROM chain_seeds
`

func (q *Queries) NextChainGroup(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextChainGroup)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const revealChainSeed = `-- name: RevealChainSeed :exec
UPDATE chain_seeds SET revealed_at = now() WHERE id = $1
`

func (q *Queries) RevealChainSeed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revealChainSeed, id)
	return err
}
