// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveChatMute = `-- name: GetActiveChatMute :one
SELECT user_id, muted_until, reason
FROM chat_mutes
WHERE user_id = $1 AND muted_until > now()
`

type GetActiveChatMuteRow struct {
	UserID     int64
	MutedUntil time.Time
	Reason     string
}

func (q *Queries) GetActiveChatMute(ctx context.Context, userID int64) (GetActiveChatMuteRow, error) {
	row := q.db.QueryRow(ctx, getActiveChatMute, userID)
	var i GetActiveChatMuteRow
	err := row.Scan(&i.UserID, &i.MutedUntil, &i.Reason)
	return i, err
}

const insertChatMessage = `-- name: InsertChatMessage :one
INSERT INTO chat_messages (user_id, kind, body)
VALUES ($1, $2, $3)
RETURNING id, user_id, kind, body, deleted, created_at
`

type InsertChatMessageParams struct {
	UserID int64
	Kind   string
	Body   string
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, insertChatMessage, arg.UserID, arg.Kind, arg.Body)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Body,
		&i.Deleted,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentChatMessages = `-- name: ListRecentChatMessages :many
SELECT m.id, m.user_id, m.kind, m.body, m.created_at,
       u.display_name, u.avatar_preset, u.avatar_version, u.role,
       u.title, u.name_effect
FROM chat_messages m
JOIN users u ON u.id = m.user_id
WHERE m.deleted = false
ORDER BY m.id DESC
LIMIT $1
`

type ListRecentChatMessagesRow struct {
	ID            int64
	UserID        int64
	Kind          string
	Body          string
	CreatedAt     time.Time
	DisplayName   string
	AvatarPreset  pgtype.Text
	AvatarVersion int64
	Role          string
	Title         string
	NameEffect    string
}

// Newest-first slice; the client renders bottom-up. System lines carry the
// acting user (winner, rainmaker, tipper) so the join fills their identity.
func (q *Queries) ListRecentChatMessages(ctx context.Context, limit int32) ([]ListRecentChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, listRecentChatMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentChatMessagesRow
	for rows.Next() {
		var i ListRecentChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Body,
			&i.CreatedAt,
			&i.DisplayName,
			&i.AvatarPreset,
			&i.AvatarVersion,
			&i.Role,
			&i.Title,
			&i.NameEffect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteChatMessage = `-- name: SoftDeleteChatMessage :execrows
UPDATE chat_messages SET deleted = true
WHERE id = $1 AND deleted = false
`

func (q *Queries) SoftDeleteChatMessage(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteChatMessage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertChatMute = `-- name: UpsertChatMute :exec
INSERT INTO chat_mutes (user_id, muted_until, reason, muted_by)
VALUES ($1, now() + make_interval(mins => $2::int), $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET muted_until = EXCLUDED.muted_until,
    reason      = EXCLUDED.reason,
    muted_by    = EXCLUDED.muted_by,
    created_at  = now()
`

type UpsertChatMuteParams struct {
	UserID  int64
	Column2 int32
	Reason  string
	MutedBy pgtype.Int8
}

func (q *Queries) UpsertChatMute(ctx context.Context, arg UpsertChatMuteParams) error {
	_, err := q.db.Exec(ctx, upsertChatMute,
		arg.UserID,
		arg.Column2,
		arg.Reason,
		arg.MutedBy,
	)
	return err
}
