// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chicken.sql

package store

import (
	"context"
	"time"
)

const getActiveChickenRoundByUser = `-- name: GetActiveChickenRoundByUser :one
SELECT id, user_id, bet_id, status, bet_credits, difficulty, lanes, crossed,
       fatal_lane, payout_credits, action_keys, server_seed_id, client_seed, nonce,
       created_at, updated_at, completed_at
FROM chicken_rounds
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveChickenRoundByUser(ctx context.Context, userID int64) (ChickenRound, error) {
	row := q.db.QueryRow(ctx, getActiveChickenRoundByUser, userID)
	var i ChickenRound
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BetID,
		&i.Status,
		&i.BetCredits,
		&i.Difficulty,
		&i.Lanes,
		&i.Crossed,
		&i.FatalLane,
		&i.PayoutCredits,
		&i.ActionKeys,
		&i.ServerSeedID,
		&i.ClientSeed,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getChickenRoundByBetID = `-- name: GetChickenRoundByBetID :one
SELECT id, user_id, bet_id, status, bet_credits, difficulty, lanes, crossed,
       fatal_lane, payout_credits, action_keys, server_seed_id, client_seed, nonce,
       created_at, updated_at, completed_at
FROM chicken_rounds
WHERE bet_id = $1
`

// Start idempotency replays land here: the idempotency key resolved to a
// transaction, the transaction to its bet, the bet to its round.
func (q *Queries) GetChickenRoundByBetID(ctx context.Context, betID int64) (ChickenRound, error) {
	row := q.db.QueryRow(ctx, getChickenRoundByBetID, betID)
	var i ChickenRound
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BetID,
		&i.Status,
		&i.BetCredits,
		&i.Difficulty,
		&i.Lanes,
		&i.Crossed,
		&i.FatalLane,
		&i.PayoutCredits,
		&i.ActionKeys,
		&i.ServerSeedID,
		&i.ClientSeed,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getChickenRoundByID = `-- name: GetChickenRoundByID :one
SELECT id, user_id, bet_id, status, bet_credits, difficulty, lanes, crossed,
       fatal_lane, payout_credits, action_keys, server_seed_id, client_seed, nonce,
       created_at, updated_at, completed_at
FROM chicken_rounds
WHERE id = $1
`

func (q *Queries) GetChickenRoundByID(ctx context.Context, id int64) (ChickenRound, error) {
	row := q.db.QueryRow(ctx, getChickenRoundByID, id)
	var i ChickenRound
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BetID,
		&i.Status,
		&i.BetCredits,
		&i.Difficulty,
		&i.Lanes,
		&i.Crossed,
		&i.FatalLane,
		&i.PayoutCredits,
		&i.ActionKeys,
		&i.ServerSeedID,
		&i.ClientSeed,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertChickenRound = `-- name: InsertChickenRound :one
INSERT INTO chicken_rounds (user_id, bet_id, status, bet_credits, difficulty,
                            lanes, crossed, fatal_lane, payout_credits, action_keys,
                            server_seed_id, client_seed, nonce)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id
`

type InsertChickenRoundParams struct {
	UserID        int64
	BetID         int64
	Status        string
	BetCredits    int64
	Difficulty    string
	Lanes         int32
	Crossed       int32
	FatalLane     int32
	PayoutCredits int64
	ActionKeys    []byte
	ServerSeedID  int64
	ClientSeed    string
	Nonce         int64
}

func (q *Queries) InsertChickenRound(ctx context.Context, arg InsertChickenRoundParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChickenRound,
		arg.UserID,
		arg.BetID,
		arg.Status,
		arg.BetCredits,
		arg.Difficulty,
		arg.Lanes,
		arg.Crossed,
		arg.FatalLane,
		arg.PayoutCredits,
		arg.ActionKeys,
		arg.ServerSeedID,
		arg.ClientSeed,
		arg.Nonce,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const saveChickenRound = `-- name: SaveChickenRound :exec
UPDATE chicken_rounds
SET status = $2,
    payout_credits = $3,
    crossed = $4,
    action_keys = $5,
    updated_at = now(),
    completed_at = $6
WHERE id = $1
`

type SaveChickenRoundParams struct {
	ID            int64
	Status        string
	PayoutCredits int64
	Crossed       int32
	ActionKeys    []byte
	CompletedAt   *time.Time
}

// Single writer per round (the wallet row lock serializes the user's
// actions), so a blind write of the full derived state is safe.
// completed_at is NULL while the round is active.
func (q *Queries) SaveChickenRound(ctx context.Context, arg SaveChickenRoundParams) error {
	_, err := q.db.Exec(ctx, saveChickenRound,
		arg.ID,
		arg.Status,
		arg.PayoutCredits,
		arg.Crossed,
		arg.ActionKeys,
		arg.CompletedAt,
	)
	return err
}

const setChickenBetSettlement = `-- name: SetChickenBetSettlement :exec
UPDATE bets
SET payout_credits = $2,
    outcome = $3
WHERE id = $1
`

type SetChickenBetSettlementParams struct {
	ID            int64
	PayoutCredits int64
	Outcome       []byte
}

// Completion (cashout or squash) fills payout and the fully-revealed outcome.
func (q *Queries) SetChickenBetSettlement(ctx context.Context, arg SetChickenBetSettlementParams) error {
	_, err := q.db.Exec(ctx, setChickenBetSettlement, arg.ID, arg.PayoutCredits, arg.Outcome)
	return err
}
