// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_tokens.sql

package store

import (
	"context"
	"time"
)

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO email_tokens (user_id, kind, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, kind, token_hash, expires_at, used_at
`

type CreateEmailTokenParams struct {
	UserID    int64
	Kind      string
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, createEmailToken,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getValidEmailToken = `-- name: GetValidEmailToken :one
SELECT id, user_id FROM email_tokens
WHERE token_hash = $1 AND kind = $2
  AND used_at IS NULL AND expires_at > now()
`

type GetValidEmailTokenParams struct {
	TokenHash string
	Kind      string
}

type GetValidEmailTokenRow struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetValidEmailToken(ctx context.Context, arg GetValidEmailTokenParams) (GetValidEmailTokenRow, error) {
	row := q.db.QueryRow(ctx, getValidEmailToken, arg.TokenHash, arg.Kind)
	var i GetValidEmailTokenRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const markEmailTokenUsed = `-- name: MarkEmailTokenUsed :exec
UPDATE email_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markEmailTokenUsed, id)
	return err
}
