// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hands.sql

package store

import (
	"context"
	"time"
)

const getActiveBlackjackHandByUser = `-- name: GetActiveBlackjackHandByUser :one
SELECT id, user_id, bet_id, status, bet_credits, payout_credits, actions,
       action_keys, hand_state, server_seed_id, client_seed, nonce,
       created_at, updated_at, completed_at
FROM blackjack_hands
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveBlackjackHandByUser(ctx context.Context, userID int64) (BlackjackHand, error) {
	row := q.db.QueryRow(ctx, getActiveBlackjackHandByUser, userID)
	var i BlackjackHand
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BetID,
		&i.Status,
		&i.BetCredits,
		&i.PayoutCredits,
		&i.Actions,
		&i.ActionKeys,
		&i.HandState,
		&i.ServerSeedID,
		&i.ClientSeed,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getBlackjackHandByBetID = `-- name: GetBlackjackHandByBetID :one
SELECT id, user_id, bet_id, status, bet_credits, payout_credits, actions,
       action_keys, hand_state, server_seed_id, client_seed, nonce,
       created_at, updated_at, completed_at
FROM blackjack_hands
WHERE bet_id = $1
`

// Deal idempotency replays land here: the idempotency key resolved to a
// transaction, the transaction to its bet, the bet to its hand.
func (q *Queries) GetBlackjackHandByBetID(ctx context.Context, betID int64) (BlackjackHand, error) {
	row := q.db.QueryRow(ctx, getBlackjackHandByBetID, betID)
	var i BlackjackHand
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BetID,
		&i.Status,
		&i.BetCredits,
		&i.PayoutCredits,
		&i.Actions,
		&i.ActionKeys,
		&i.HandState,
		&i.ServerSeedID,
		&i.ClientSeed,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getBlackjackHandByID = `-- name: GetBlackjackHandByID :one
SELECT id, user_id, bet_id, status, bet_credits, payout_credits, actions,
       action_keys, hand_state, server_seed_id, client_seed, nonce,
       created_at, updated_at, completed_at
FROM blackjack_hands
WHERE id = $1
`

func (q *Queries) GetBlackjackHandByID(ctx context.Context, id int64) (BlackjackHand, error) {
	row := q.db.QueryRow(ctx, getBlackjackHandByID, id)
	var i BlackjackHand
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BetID,
		&i.Status,
		&i.BetCredits,
		&i.PayoutCredits,
		&i.Actions,
		&i.ActionKeys,
		&i.HandState,
		&i.ServerSeedID,
		&i.ClientSeed,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertBlackjackHand = `-- name: InsertBlackjackHand :one
INSERT INTO blackjack_hands (user_id, bet_id, status, bet_credits,
                             payout_credits, actions, action_keys, hand_state,
                             server_seed_id, client_seed, nonce)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertBlackjackHandParams struct {
	UserID        int64
	BetID         int64
	Status        string
	BetCredits    int64
	PayoutCredits int64
	Actions       []byte
	ActionKeys    []byte
	HandState     []byte
	ServerSeedID  int64
	ClientSeed    string
	Nonce         int64
}

func (q *Queries) InsertBlackjackHand(ctx context.Context, arg InsertBlackjackHandParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBlackjackHand,
		arg.UserID,
		arg.BetID,
		arg.Status,
		arg.BetCredits,
		arg.PayoutCredits,
		arg.Actions,
		arg.ActionKeys,
		arg.HandState,
		arg.ServerSeedID,
		arg.ClientSeed,
		arg.Nonce,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const saveBlackjackHand = `-- name: SaveBlackjackHand :exec
UPDATE blackjack_hands
SET status = $2,
    bet_credits = $3,
    payout_credits = $4,
    actions = $5,
    action_keys = $6,
    hand_state = $7,
    updated_at = now(),
    completed_at = $8
WHERE id = $1
`

type SaveBlackjackHandParams struct {
	ID            int64
	Status        string
	BetCredits    int64
	PayoutCredits int64
	Actions       []byte
	ActionKeys    []byte
	HandState     []byte
	CompletedAt   *time.Time
}

// Single writer per hand (the wallet row lock serializes the user's actions),
// so a blind write of the full derived state is safe. completed_at is NULL
// while the hand is active.
func (q *Queries) SaveBlackjackHand(ctx context.Context, arg SaveBlackjackHandParams) error {
	_, err := q.db.Exec(ctx, saveBlackjackHand,
		arg.ID,
		arg.Status,
		arg.BetCredits,
		arg.PayoutCredits,
		arg.Actions,
		arg.ActionKeys,
		arg.HandState,
		arg.CompletedAt,
	)
	return err
}

const setBlackjackBetSettlement = `-- name: SetBlackjackBetSettlement :exec
UPDATE bets
SET bet_credits = $2,
    payout_credits = $3,
    outcome = $4
WHERE id = $1
`

type SetBlackjackBetSettlementParams struct {
	ID            int64
	BetCredits    int64
	PayoutCredits int64
	Outcome       []byte
}

// Doubles raise the staked amount; completion fills payout and outcome.
func (q *Queries) SetBlackjackBetSettlement(ctx context.Context, arg SetBlackjackBetSettlementParams) error {
	_, err := q.db.Exec(ctx, setBlackjackBetSettlement,
		arg.ID,
		arg.BetCredits,
		arg.PayoutCredits,
		arg.Outcome,
	)
	return err
}
