// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package store

import (
	"context"
)

const ping = `-- name: Ping :execrows

SELECT 1
`

// +goose Up
// +goose Down
func (q *Queries) Ping(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, ping)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
