// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserBiggestWin = `-- name: GetUserBiggestWin :one
SELECT COALESCE(MAX(payout_credits - bet_credits), 0)::bigint AS value
FROM bets
WHERE user_id = $1
`

// Player-card stat: best single-bet net result, all time.
func (q *Queries) GetUserBiggestWin(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getUserBiggestWin, userID)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const leaderboardBiggestWin = `-- name: LeaderboardBiggestWin :many

SELECT b.user_id, u.display_name, u.avatar_preset, u.avatar_version,
       MAX(b.payout_credits - b.bet_credits)::bigint AS value
FROM bets b
JOIN users u ON u.id = b.user_id
WHERE u.status = 'active'
  AND b.created_at >= now() - ($1::text)::interval
GROUP BY b.user_id, u.display_name, u.avatar_preset, u.avatar_version
ORDER BY value DESC, b.user_id ASC
`

type LeaderboardBiggestWinRow struct {
	UserID        int64
	DisplayName   string
	AvatarPreset  pgtype.Text
	AvatarVersion int64
	Value         int64
}

// Leaderboard aggregates over settled bets. @span is a Postgres interval
// literal as text ('24 hours', '7 days', '1000 years' for all-time).
// sqlc's offline engine cannot analyze CTEs or FROM-subqueries, so each
// metric is one unbounded aggregate; the handler slices the top 20 and
// finds the caller's rank from the same rows (the player base is small).
func (q *Queries) LeaderboardBiggestWin(ctx context.Context, span string) ([]LeaderboardBiggestWinRow, error) {
	rows, err := q.db.Query(ctx, leaderboardBiggestWin, span)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardBiggestWinRow
	for rows.Next() {
		var i LeaderboardBiggestWinRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.AvatarPreset,
			&i.AvatarVersion,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leaderboardNetProfit = `-- name: LeaderboardNetProfit :many
SELECT b.user_id, u.display_name, u.avatar_preset, u.avatar_version,
       SUM(payout_credits - bet_credits)::bigint AS value
FROM bets b
JOIN users u ON u.id = b.user_id
WHERE u.status = 'active'
  AND b.created_at >= now() - ($1::text)::interval
GROUP BY b.user_id, u.display_name, u.avatar_preset, u.avatar_version
ORDER BY value DESC, b.user_id ASC
`

type LeaderboardNetProfitRow struct {
	UserID        int64
	DisplayName   string
	AvatarPreset  pgtype.Text
	AvatarVersion int64
	Value         int64
}

func (q *Queries) LeaderboardNetProfit(ctx context.Context, span string) ([]LeaderboardNetProfitRow, error) {
	rows, err := q.db.Query(ctx, leaderboardNetProfit, span)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardNetProfitRow
	for rows.Next() {
		var i LeaderboardNetProfitRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.AvatarPreset,
			&i.AvatarVersion,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leaderboardWagered = `-- name: LeaderboardWagered :many
SELECT b.user_id, u.display_name, u.avatar_preset, u.avatar_version,
       SUM(b.bet_credits)::bigint AS value
FROM bets b
JOIN users u ON u.id = b.user_id
WHERE u.status = 'active'
  AND b.created_at >= now() - ($1::text)::interval
GROUP BY b.user_id, u.display_name, u.avatar_preset, u.avatar_version
ORDER BY value DESC, b.user_id ASC
`

type LeaderboardWageredRow struct {
	UserID        int64
	DisplayName   string
	AvatarPreset  pgtype.Text
	AvatarVersion int64
	Value         int64
}

func (q *Queries) LeaderboardWagered(ctx context.Context, span string) ([]LeaderboardWageredRow, error) {
	rows, err := q.db.Query(ctx, leaderboardWagered, span)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardWageredRow
	for rows.Next() {
		var i LeaderboardWageredRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.AvatarPreset,
			&i.AvatarVersion,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
