// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mines.sql

package store

import (
	"context"
	"time"
)

const getActiveMinesRoundByUser = `-- name: GetActiveMinesRoundByUser :one
SELECT id, user_id, bet_id, status, bet_credits, mine_count, payout_credits,
       mines, revealed, action_keys, server_seed_id, client_seed, nonce,
       created_at, updated_at, completed_at
FROM mines_rounds
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveMinesRoundByUser(ctx context.Context, userID int64) (MinesRound, error) {
	row := q.db.QueryRow(ctx, getActiveMinesRoundByUser, userID)
	var i MinesRound
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BetID,
		&i.Status,
		&i.BetCredits,
		&i.MineCount,
		&i.PayoutCredits,
		&i.Mines,
		&i.Revealed,
		&i.ActionKeys,
		&i.ServerSeedID,
		&i.ClientSeed,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getMinesRoundByBetID = `-- name: GetMinesRoundByBetID :one
SELECT id, user_id, bet_id, status, bet_credits, mine_count, payout_credits,
       mines, revealed, action_keys, server_seed_id, client_seed, nonce,
       created_at, updated_at, completed_at
FROM mines_rounds
WHERE bet_id = $1
`

// Start idempotency replays land here: the idempotency key resolved to a
// transaction, the transaction to its bet, the bet to its round.
func (q *Queries) GetMinesRoundByBetID(ctx context.Context, betID int64) (MinesRound, error) {
	row := q.db.QueryRow(ctx, getMinesRoundByBetID, betID)
	var i MinesRound
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BetID,
		&i.Status,
		&i.BetCredits,
		&i.MineCount,
		&i.PayoutCredits,
		&i.Mines,
		&i.Revealed,
		&i.ActionKeys,
		&i.ServerSeedID,
		&i.ClientSeed,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getMinesRoundByID = `-- name: GetMinesRoundByID :one
SELECT id, user_id, bet_id, status, bet_credits, mine_count, payout_credits,
       mines, revealed, action_keys, server_seed_id, client_seed, nonce,
       created_at, updated_at, completed_at
FROM mines_rounds
WHERE id = $1
`

func (q *Queries) GetMinesRoundByID(ctx context.Context, id int64) (MinesRound, error) {
	row := q.db.QueryRow(ctx, getMinesRoundByID, id)
	var i MinesRound
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BetID,
		&i.Status,
		&i.BetCredits,
		&i.MineCount,
		&i.PayoutCredits,
		&i.Mines,
		&i.Revealed,
		&i.ActionKeys,
		&i.ServerSeedID,
		&i.ClientSeed,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertMinesRound = `-- name: InsertMinesRound :one
INSERT INTO mines_rounds (user_id, bet_id, status, bet_credits, mine_count,
                          payout_credits, mines, revealed, action_keys,
                          server_seed_id, client_seed, nonce)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type InsertMinesRoundParams struct {
	UserID        int64
	BetID         int64
	Status        string
	BetCredits    int64
	MineCount     int32
	PayoutCredits int64
	Mines         []byte
	Revealed      []byte
	ActionKeys    []byte
	ServerSeedID  int64
	ClientSeed    string
	Nonce         int64
}

func (q *Queries) InsertMinesRound(ctx context.Context, arg InsertMinesRoundParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMinesRound,
		arg.UserID,
		arg.BetID,
		arg.Status,
		arg.BetCredits,
		arg.MineCount,
		arg.PayoutCredits,
		arg.Mines,
		arg.Revealed,
		arg.ActionKeys,
		arg.ServerSeedID,
		arg.ClientSeed,
		arg.Nonce,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const saveMinesRound = `-- name: SaveMinesRound :exec
UPDATE mines_rounds
SET status = $2,
    payout_credits = $3,
    revealed = $4,
    action_keys = $5,
    updated_at = now(),
    completed_at = $6
WHERE id = $1
`

type SaveMinesRoundParams struct {
	ID            int64
	Status        string
	PayoutCredits int64
	Revealed      []byte
	ActionKeys    []byte
	CompletedAt   *time.Time
}

// Single writer per round (the wallet row lock serializes the user's
// actions), so a blind write of the full derived state is safe.
// completed_at is NULL while the round is active.
func (q *Queries) SaveMinesRound(ctx context.Context, arg SaveMinesRoundParams) error {
	_, err := q.db.Exec(ctx, saveMinesRound,
		arg.ID,
		arg.Status,
		arg.PayoutCredits,
		arg.Revealed,
		arg.ActionKeys,
		arg.CompletedAt,
	)
	return err
}

const setMinesBetSettlement = `-- name: SetMinesBetSettlement :exec
UPDATE bets
SET payout_credits = $2,
    outcome = $3
WHERE id = $1
`

type SetMinesBetSettlementParams struct {
	ID            int64
	PayoutCredits int64
	Outcome       []byte
}

// Completion (cashout or bust) fills payout and the fully-revealed outcome.
func (q *Queries) SetMinesBetSettlement(ctx context.Context, arg SetMinesBetSettlementParams) error {
	_, err := q.db.Exec(ctx, setMinesBetSettlement, arg.ID, arg.PayoutCredits, arg.Outcome)
	return err
}
