// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64
	ActorUserID pgtype.Int8
	Action      string
	TargetType  pgtype.Text
	TargetID    pgtype.Int8
	Metadata    []byte
	CreatedAt   time.Time
}

type Bet struct {
	ID            int64
	UserID        int64
	GameID        string
	RoundID       int64
	BetCredits    int64
	PayoutCredits int64
	ServerSeedID  int64
	ClientSeed    string
	Nonce         int64
	Outcome       []byte
	CreatedAt     time.Time
}

type ChainSeed struct {
	ID         int64
	Index      int64
	SeedHash   string
	SeedPlain  pgtype.Text
	RevealedAt *time.Time
}

type EmailToken struct {
	ID        int64
	UserID    int64
	Kind      string
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type OauthIdentity struct {
	Provider       string
	ProviderUserID string
	UserID         int64
}

type Room struct {
	ID       int64
	GameID   string
	Slug     string
	Name     string
	MinBet   int64
	MaxBet   int64
	Capacity int32
	IsActive bool
}

type Round struct {
	ID          int64
	RoomID      pgtype.Int8
	GameID      string
	ChainSeedID pgtype.Int8
	Salt        string
	State       string
	Result      []byte
	OpenedAt    time.Time
	LockedAt    *time.Time
	SettledAt   *time.Time
}

type ServerSeed struct {
	ID         int64
	UserID     int64
	SeedHash   string
	SeedPlain  pgtype.Text
	IsActive   bool
	CreatedAt  time.Time
	RevealedAt *time.Time
	ClientSeed string
	Nonce      int64
}

type Session struct {
	ID         int64
	UserID     int64
	TokenHash  string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastSeenAt time.Time
	Ip         pgtype.Text
	UserAgent  pgtype.Text
	RevokedAt  *time.Time
}

type Theme struct {
	ID        int64
	UserID    int64
	Name      string
	Palette   []byte
	Sprites   []byte
	CreatedAt time.Time
}

type Transaction struct {
	ID             int64
	WalletID       int64
	Kind           string
	AmountCredits  int64
	BetID          pgtype.Int8
	IdempotencyKey string
	CreatedAt      time.Time
}

type User struct {
	ID              int64
	CreatedAt       time.Time
	IsGuest         bool
	DisplayName     string
	Email           *string
	PasswordHash    pgtype.Text
	EmailVerifiedAt *time.Time
	Role            string
	Status          string
	StatusUntil     *time.Time
}

type Wallet struct {
	UserID         int64
	BalanceCredits int64
}
