// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc.sql

package store

import (
	"context"
	"time"
)

const createUserFromKeycloak = `-- name: CreateUserFromKeycloak :one
INSERT INTO users (display_name, email, email_verified_at, is_guest)
VALUES ($1, $2, $3, false)
RETURNING id, created_at, is_guest, display_name, email, password_hash,
          email_verified_at, role, status, status_until,
          avatar_preset, avatar_version, display_name_updated_at
`

type CreateUserFromKeycloakParams struct {
	DisplayName     string
	Email           *string
	EmailVerifiedAt *time.Time
}

func (q *Queries) CreateUserFromKeycloak(ctx context.Context, arg CreateUserFromKeycloakParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserFromKeycloak, arg.DisplayName, arg.Email, arg.EmailVerifiedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.IsGuest,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.Status,
		&i.StatusUntil,
		&i.AvatarPreset,
		&i.AvatarVersion,
		&i.DisplayNameUpdatedAt,
	)
	return i, err
}

const getOauthIdentity = `-- name: GetOauthIdentity :one
SELECT provider, provider_user_id, user_id
FROM oauth_identities
WHERE provider = $1 AND provider_user_id = $2
`

type GetOauthIdentityParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetOauthIdentity(ctx context.Context, arg GetOauthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOauthIdentity, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(&i.Provider, &i.ProviderUserID, &i.UserID)
	return i, err
}

const insertOauthIdentity = `-- name: InsertOauthIdentity :exec
INSERT INTO oauth_identities (provider, provider_user_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (provider, provider_user_id) DO NOTHING
`

type InsertOauthIdentityParams struct {
	Provider       string
	ProviderUserID string
	UserID         int64
}

func (q *Queries) InsertOauthIdentity(ctx context.Context, arg InsertOauthIdentityParams) error {
	_, err := q.db.Exec(ctx, insertOauthIdentity, arg.Provider, arg.ProviderUserID, arg.UserID)
	return err
}

const upgradeGuestForKeycloak = `-- name: UpgradeGuestForKeycloak :one
UPDATE users
SET display_name      = COALESCE(NULLIF($2::text, ''), display_name),
    email             = COALESCE($3::citext, email),
    email_verified_at = COALESCE($4, email_verified_at),
    is_guest          = false
WHERE id = $1 AND is_guest = true
RETURNING id, created_at, is_guest, display_name, email, password_hash,
          email_verified_at, role, status, status_until,
          avatar_preset, avatar_version, display_name_updated_at
`

type UpgradeGuestForKeycloakParams struct {
	ID              int64
	DisplayName     string
	Email           *string
	EmailVerifiedAt *time.Time
}

// Guest upgrade in place: the same row keeps its wallet, bets, and seeds.
func (q *Queries) UpgradeGuestForKeycloak(ctx context.Context, arg UpgradeGuestForKeycloakParams) (User, error) {
	row := q.db.QueryRow(ctx, upgradeGuestForKeycloak,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.EmailVerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.IsGuest,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.Status,
		&i.StatusUntil,
		&i.AvatarPreset,
		&i.AvatarVersion,
		&i.DisplayNameUpdatedAt,
	)
	return i, err
}
