// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personalization.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserPrefs = `-- name: GetUserPrefs :one
SELECT personalize_enabled
FROM user_prefs
WHERE user_id = $1
`

func (q *Queries) GetUserPrefs(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, getUserPrefs, userID)
	var personalize_enabled bool
	err := row.Scan(&personalize_enabled)
	return personalize_enabled, err
}

const insertPlayerEvent = `-- name: InsertPlayerEvent :exec
INSERT INTO player_events (user_id, session_id, event_type, game_id, context)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPlayerEventParams struct {
	UserID    int64
	SessionID pgtype.Int8
	EventType string
	GameID    string
	Context   []byte
}

func (q *Queries) InsertPlayerEvent(ctx context.Context, arg InsertPlayerEventParams) error {
	_, err := q.db.Exec(ctx, insertPlayerEvent,
		arg.UserID,
		arg.SessionID,
		arg.EventType,
		arg.GameID,
		arg.Context,
	)
	return err
}

const listGameMetadata = `-- name: ListGameMetadata :many

SELECT game_id, category, collection, tags, is_new_until, blurb
FROM game_metadata
ORDER BY game_id
`

// Personalization: catalog metadata, the launch-event sink, the lobby
// preference, and the affinity aggregates behind the recommendation scorer.
func (q *Queries) ListGameMetadata(ctx context.Context) ([]GameMetadatum, error) {
	rows, err := q.db.Query(ctx, listGameMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameMetadatum
	for rows.Next() {
		var i GameMetadatum
		if err := rows.Scan(
			&i.GameID,
			&i.Category,
			&i.Collection,
			&i.Tags,
			&i.IsNewUntil,
			&i.Blurb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trendingBets = `-- name: TrendingBets :many
SELECT game_id, COUNT(*)::bigint AS hits
FROM bets
WHERE created_at >= now() - interval '24 hours'
GROUP BY game_id
`

type TrendingBetsRow struct {
	GameID string
	Hits   int64
}

func (q *Queries) TrendingBets(ctx context.Context) ([]TrendingBetsRow, error) {
	rows, err := q.db.Query(ctx, trendingBets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrendingBetsRow
	for rows.Next() {
		var i TrendingBetsRow
		if err := rows.Scan(&i.GameID, &i.Hits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trendingLaunches = `-- name: TrendingLaunches :many
SELECT game_id, COUNT(*)::bigint AS hits
FROM player_events
WHERE event_type = 'launch'
  AND created_at >= now() - interval '24 hours'
GROUP BY game_id
`

type TrendingLaunchesRow struct {
	GameID string
	Hits   int64
}

func (q *Queries) TrendingLaunches(ctx context.Context) ([]TrendingLaunchesRow, error) {
	rows, err := q.db.Query(ctx, trendingLaunches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrendingLaunchesRow
	for rows.Next() {
		var i TrendingLaunchesRow
		if err := rows.Scan(&i.GameID, &i.Hits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserPrefs = `-- name: UpsertUserPrefs :one
INSERT INTO user_prefs (user_id, personalize_enabled, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (user_id) DO UPDATE
SET personalize_enabled = EXCLUDED.personalize_enabled,
    updated_at = now()
RETURNING personalize_enabled
`

type UpsertUserPrefsParams struct {
	UserID             int64
	PersonalizeEnabled bool
}

func (q *Queries) UpsertUserPrefs(ctx context.Context, arg UpsertUserPrefsParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertUserPrefs, arg.UserID, arg.PersonalizeEnabled)
	var personalize_enabled bool
	err := row.Scan(&personalize_enabled)
	return personalize_enabled, err
}

const userGameAffinity = `-- name: UserGameAffinity :many
SELECT game_id,
       COUNT(*)::bigint AS bet_count,
       COALESCE(SUM(bet_credits), 0)::bigint AS wagered,
       COALESCE(SUM(payout_credits - bet_credits), 0)::bigint AS net,
       MAX(created_at) AS last_played
FROM bets
WHERE user_id = $1
  AND created_at >= now() - ($2::text)::interval
GROUP BY game_id
`

type UserGameAffinityParams struct {
	UserID int64
	Span   string
}

type UserGameAffinityRow struct {
	GameID     string
	BetCount   int64
	Wagered    int64
	Net        int64
	LastPlayed interface{}
}

func (q *Queries) UserGameAffinity(ctx context.Context, arg UserGameAffinityParams) ([]UserGameAffinityRow, error) {
	rows, err := q.db.Query(ctx, userGameAffinity, arg.UserID, arg.Span)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGameAffinityRow
	for rows.Next() {
		var i UserGameAffinityRow
		if err := rows.Scan(
			&i.GameID,
			&i.BetCount,
			&i.Wagered,
			&i.Net,
			&i.LastPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userRecentLaunches = `-- name: UserRecentLaunches :many
SELECT game_id, MAX(created_at) AS last_at
FROM player_events
WHERE user_id = $1
  AND event_type = 'launch'
  AND created_at >= now() - ($2::text)::interval
GROUP BY game_id
`

type UserRecentLaunchesParams struct {
	UserID int64
	Span   string
}

type UserRecentLaunchesRow struct {
	GameID string
	LastAt interface{}
}

// Launches carry signal for players (guests especially) who look around
// without settling a bet.
func (q *Queries) UserRecentLaunches(ctx context.Context, arg UserRecentLaunchesParams) ([]UserRecentLaunchesRow, error) {
	rows, err := q.db.Query(ctx, userRecentLaunches, arg.UserID, arg.Span)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRecentLaunchesRow
	for rows.Next() {
		var i UserRecentLaunchesRow
		if err := rows.Scan(&i.GameID, &i.LastAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userStakeStats = `-- name: UserStakeStats :one
SELECT COALESCE(AVG(CASE WHEN created_at >= now() - interval '1 hour' THEN bet_credits END), 0)::bigint AS avg_bet_1h,
       COALESCE(AVG(CASE WHEN created_at >= now() - interval '7 days' THEN bet_credits END), 0)::bigint AS avg_bet_7d,
       COALESCE(SUM(CASE WHEN created_at >= now() - interval '24 hours' THEN payout_credits - bet_credits ELSE 0 END), 0)::bigint AS net_24h
FROM bets
WHERE user_id = $1
`

type UserStakeStatsRow struct {
	AvgBet1h int64
	AvgBet7d int64
	Net24h   int64
}

// Stake pattern for the safer-play suppression gate. CASE, not FILTER:
// the sqlc offline engine analyzes it reliably.
func (q *Queries) UserStakeStats(ctx context.Context, userID int64) (UserStakeStatsRow, error) {
	row := q.db.QueryRow(ctx, userStakeStats, userID)
	var i UserStakeStatsRow
	err := row.Scan(&i.AvgBet1h, &i.AvgBet7d, &i.Net24h)
	return i, err
}
