// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package store

import (
	"context"
)

const getRoomBySlug = `-- name: GetRoomBySlug :one
SELECT id, game_id, slug, name, min_bet, max_bet, capacity, is_active
FROM rooms
WHERE slug = $1 AND is_active
`

func (q *Queries) GetRoomBySlug(ctx context.Context, slug string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomBySlug, slug)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Slug,
		&i.Name,
		&i.MinBet,
		&i.MaxBet,
		&i.Capacity,
		&i.IsActive,
	)
	return i, err
}

const listActiveRooms = `-- name: ListActiveRooms :many
SELECT id, game_id, slug, name, min_bet, max_bet, capacity, is_active
FROM rooms
WHERE is_active
ORDER BY id
`

func (q *Queries) ListActiveRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listActiveRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Slug,
			&i.Name,
			&i.MinBet,
			&i.MaxBet,
			&i.Capacity,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
