// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: round_bets.sql

package store

import (
	"context"
)

const insertRoundBet = `-- name: InsertRoundBet :one
INSERT INTO bets (user_id, game_id, round_id, bet_credits, server_seed_id, client_seed, nonce, action, auto_cashout_hundredths)
VALUES ($1, 'crash', $2, $3, NULL, NULL, NULL, 'bet', $4)
RETURNING id
`

type InsertRoundBetParams struct {
	UserID                int64
	RoundID               int64
	BetCredits            int64
	AutoCashoutHundredths int64
}

func (q *Queries) InsertRoundBet(ctx context.Context, arg InsertRoundBetParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRoundBet,
		arg.UserID,
		arg.RoundID,
		arg.BetCredits,
		arg.AutoCashoutHundredths,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markBetCashout = `-- name: MarkBetCashout :exec
UPDATE bets SET cashout_hundredths = $2 WHERE id = $1
`

type MarkBetCashoutParams struct {
	ID                int64
	CashoutHundredths int64
}

func (q *Queries) MarkBetCashout(ctx context.Context, arg MarkBetCashoutParams) error {
	_, err := q.db.Exec(ctx, markBetCashout, arg.ID, arg.CashoutHundredths)
	return err
}

const markBetCashoutByRound = `-- name: MarkBetCashoutByRound :exec
UPDATE bets SET cashout_hundredths = $3
WHERE round_id = $1 AND user_id = $2 AND action = 'bet'
`

type MarkBetCashoutByRoundParams struct {
	RoundID           int64
	UserID            int64
	CashoutHundredths int64
}

func (q *Queries) MarkBetCashoutByRound(ctx context.Context, arg MarkBetCashoutByRoundParams) error {
	_, err := q.db.Exec(ctx, markBetCashoutByRound, arg.RoundID, arg.UserID, arg.CashoutHundredths)
	return err
}

const setBetPayout = `-- name: SetBetPayout :exec
UPDATE bets SET payout_credits = $2 WHERE id = $1
`

type SetBetPayoutParams struct {
	ID            int64
	PayoutCredits int64
}

func (q *Queries) SetBetPayout(ctx context.Context, arg SetBetPayoutParams) error {
	_, err := q.db.Exec(ctx, setBetPayout, arg.ID, arg.PayoutCredits)
	return err
}
