// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rounds.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (room_id, game_id, chain_seed_id, salt, state)
VALUES ($1, $2, $3, $4, 'betting_open')
RETURNING id
`

type CreateRoundParams struct {
	RoomID      pgtype.Int8
	GameID      string
	ChainSeedID pgtype.Int8
	Salt        string
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (int64, error) {
	row := q.db.QueryRow(ctx, createRound,
		arg.RoomID,
		arg.GameID,
		arg.ChainSeedID,
		arg.Salt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRoundByID = `-- name: GetRoundByID :one
SELECT id, room_id, game_id, chain_seed_id, salt, state, result, opened_at, locked_at, settled_at
FROM rounds
WHERE id = $1
`

func (q *Queries) GetRoundByID(ctx context.Context, id int64) (Round, error) {
	row := q.db.QueryRow(ctx, getRoundByID, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.GameID,
		&i.ChainSeedID,
		&i.Salt,
		&i.State,
		&i.Result,
		&i.OpenedAt,
		&i.LockedAt,
		&i.SettledAt,
	)
	return i, err
}

const setRoundResult = `-- name: SetRoundResult :exec
UPDATE rounds SET state = 'settled', result = $2, settled_at = now() WHERE id = $1
`

type SetRoundResultParams struct {
	ID     int64
	Result []byte
}

func (q *Queries) SetRoundResult(ctx context.Context, arg SetRoundResultParams) error {
	_, err := q.db.Exec(ctx, setRoundResult, arg.ID, arg.Result)
	return err
}

const setRoundState = `-- name: SetRoundState :exec
UPDATE rounds SET state = $2 WHERE id = $1
`

type SetRoundStateParams struct {
	ID    int64
	State string
}

func (q *Queries) SetRoundState(ctx context.Context, arg SetRoundStateParams) error {
	_, err := q.db.Exec(ctx, setRoundState, arg.ID, arg.State)
	return err
}
