// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seeds.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServerSeed = `-- name: CreateServerSeed :one
INSERT INTO server_seeds (user_id, seed_hash, seed_plain, is_active, client_seed)
VALUES ($1, $2, $3, true, $4)
RETURNING id, user_id, seed_hash, seed_plain, is_active, created_at, revealed_at, client_seed, nonce
`

type CreateServerSeedParams struct {
	UserID     int64
	SeedHash   string
	SeedPlain  pgtype.Text
	ClientSeed string
}

func (q *Queries) CreateServerSeed(ctx context.Context, arg CreateServerSeedParams) (ServerSeed, error) {
	row := q.db.QueryRow(ctx, createServerSeed,
		arg.UserID,
		arg.SeedHash,
		arg.SeedPlain,
		arg.ClientSeed,
	)
	var i ServerSeed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeedHash,
		&i.SeedPlain,
		&i.IsActive,
		&i.CreatedAt,
		&i.RevealedAt,
		&i.ClientSeed,
		&i.Nonce,
	)
	return i, err
}

const getActiveServerSeed = `-- name: GetActiveServerSeed :one
SELECT id, user_id, seed_hash, seed_plain, is_active, created_at, revealed_at, client_seed, nonce
FROM server_seeds
WHERE user_id = $1 AND is_active = true
`

func (q *Queries) GetActiveServerSeed(ctx context.Context, userID int64) (ServerSeed, error) {
	row := q.db.QueryRow(ctx, getActiveServerSeed, userID)
	var i ServerSeed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeedHash,
		&i.SeedPlain,
		&i.IsActive,
		&i.CreatedAt,
		&i.RevealedAt,
		&i.ClientSeed,
		&i.Nonce,
	)
	return i, err
}

const getServerSeedByID = `-- name: GetServerSeedByID :one
SELECT id, user_id, seed_hash, seed_plain, is_active, created_at, revealed_at, client_seed, nonce
FROM server_seeds
WHERE id = $1
`

func (q *Queries) GetServerSeedByID(ctx context.Context, id int64) (ServerSeed, error) {
	row := q.db.QueryRow(ctx, getServerSeedByID, id)
	var i ServerSeed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeedHash,
		&i.SeedPlain,
		&i.IsActive,
		&i.CreatedAt,
		&i.RevealedAt,
		&i.ClientSeed,
		&i.Nonce,
	)
	return i, err
}

const incrementSeedNonce = `-- name: IncrementSeedNonce :one
UPDATE server_seeds
SET nonce = nonce + 1
WHERE id = $1 AND is_active = true
RETURNING nonce
`

// Called inside the play transaction so concurrent bets cannot share a
// nonce; UNIQUE (server_seed_id, nonce) backstops this.
func (q *Queries) IncrementSeedNonce(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, incrementSeedNonce, id)
	var nonce int64
	err := row.Scan(&nonce)
	return nonce, err
}

const revealAndDeactivateServerSeed = `-- name: RevealAndDeactivateServerSeed :exec
UPDATE server_seeds
SET is_active = false, revealed_at = now()
WHERE id = $1
`

// seed_plain is stored (the server needs it to derive outcomes) but is only
// exposed to the player once revealed, on rotation.
func (q *Queries) RevealAndDeactivateServerSeed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revealAndDeactivateServerSeed, id)
	return err
}

const updateClientSeed = `-- name: UpdateClientSeed :exec
UPDATE server_seeds
SET client_seed = $2
WHERE id = $1 AND is_active = true
`

type UpdateClientSeedParams struct {
	ID         int64
	ClientSeed string
}

func (q *Queries) UpdateClientSeed(ctx context.Context, arg UpdateClientSeedParams) error {
	_, err := q.db.Exec(ctx, updateClientSeed, arg.ID, arg.ClientSeed)
	return err
}
