// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, created_at, expires_at, last_seen_at, ip, user_agent, revoked_at
`

type CreateSessionParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt time.Time
	Ip        pgtype.Text
	UserAgent pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT s.id AS session_id, s.expires_at, s.last_seen_at,
       u.id AS user_id, u.is_guest, u.display_name, u.email,
       u.email_verified_at, u.role, u.status, u.created_at AS user_created_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
`

type GetActiveSessionByTokenHashRow struct {
	SessionID       int64
	ExpiresAt       time.Time
	LastSeenAt      time.Time
	UserID          int64
	IsGuest         bool
	DisplayName     string
	Email           *string
	EmailVerifiedAt *time.Time
	Role            string
	Status          string
	UserCreatedAt   time.Time
}

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenHash string) (GetActiveSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, tokenHash)
	var i GetActiveSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.UserID,
		&i.IsGuest,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.Status,
		&i.UserCreatedAt,
	)
	return i, err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE sessions
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeSessionByID, id)
	return err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSessionByTokenHash, tokenHash)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = $2,
    expires_at = LEAST($2 + interval '30 days', created_at + interval '90 days')
WHERE id = $1
`

type TouchSessionParams struct {
	ID         int64
	LastSeenAt time.Time
}

// Sliding expiry: extend by the TTL on activity, capped by an absolute
// lifetime measured from session creation.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.LastSeenAt)
	return err
}
