// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shop.sql

package store

import (
	"context"
	"time"
)

const getActiveShopItem = `-- name: GetActiveShopItem :one
SELECT id, kind, name, blurb, price_credits, rarity, payload
FROM shop_items
WHERE id = $1 AND is_active
`

type GetActiveShopItemRow struct {
	ID           string
	Kind         string
	Name         string
	Blurb        string
	PriceCredits int64
	Rarity       string
	Payload      []byte
}

func (q *Queries) GetActiveShopItem(ctx context.Context, id string) (GetActiveShopItemRow, error) {
	row := q.db.QueryRow(ctx, getActiveShopItem, id)
	var i GetActiveShopItemRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Blurb,
		&i.PriceCredits,
		&i.Rarity,
		&i.Payload,
	)
	return i, err
}

const hasInventoryItem = `-- name: HasInventoryItem :one
SELECT EXISTS (
    SELECT 1 FROM user_inventory WHERE user_id = $1 AND item_id = $2
) AS owned
`

type HasInventoryItemParams struct {
	UserID int64
	ItemID string
}

func (q *Queries) HasInventoryItem(ctx context.Context, arg HasInventoryItemParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasInventoryItem, arg.UserID, arg.ItemID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const insertInventoryItem = `-- name: InsertInventoryItem :execrows
INSERT INTO user_inventory (user_id, item_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertInventoryItemParams struct {
	UserID int64
	ItemID string
}

// The (user_id, item_id) primary key backstops double-grants; a conflicting
// retry is a no-op so idempotency replays stay harmless.
func (q *Queries) InsertInventoryItem(ctx context.Context, arg InsertInventoryItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInventoryItem, arg.UserID, arg.ItemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveEmotePacks = `-- name: ListActiveEmotePacks :many
SELECT id, payload
FROM shop_items
WHERE kind = 'emote_pack' AND is_active
`

type ListActiveEmotePacksRow struct {
	ID      string
	Payload []byte
}

// The pack-gated emote set, for the server-side wheel gate: each row maps a
// pack item id to the emote ids it unlocks. Any emote id NOT listed in an
// active pack is free to send.
func (q *Queries) ListActiveEmotePacks(ctx context.Context) ([]ListActiveEmotePacksRow, error) {
	rows, err := q.db.Query(ctx, listActiveEmotePacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveEmotePacksRow
	for rows.Next() {
		var i ListActiveEmotePacksRow
		if err := rows.Scan(&i.ID, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveShopItems = `-- name: ListActiveShopItems :many

SELECT id, kind, name, blurb, price_credits, rarity, payload, sort
FROM shop_items
WHERE is_active
ORDER BY kind, sort, price_credits
`

type ListActiveShopItemsRow struct {
	ID           string
	Kind         string
	Name         string
	Blurb        string
	PriceCredits int64
	Rarity       string
	Payload      []byte
	Sort         int32
}

// The Vault shop. Purchases never touch this file's money paths — the debit
// rides the wallet ledger (kind 'shop_purchase'); these are catalog/ownership
// reads plus the inventory grant inside the purchase transaction.
func (q *Queries) ListActiveShopItems(ctx context.Context) ([]ListActiveShopItemsRow, error) {
	rows, err := q.db.Query(ctx, listActiveShopItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveShopItemsRow
	for rows.Next() {
		var i ListActiveShopItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Blurb,
			&i.PriceCredits,
			&i.Rarity,
			&i.Payload,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventory = `-- name: ListInventory :many
SELECT item_id, acquired_at
FROM user_inventory
WHERE user_id = $1
ORDER BY acquired_at DESC, item_id
`

type ListInventoryRow struct {
	ItemID     string
	AcquiredAt time.Time
}

func (q *Queries) ListInventory(ctx context.Context, userID int64) ([]ListInventoryRow, error) {
	rows, err := q.db.Query(ctx, listInventory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryRow
	for rows.Next() {
		var i ListInventoryRow
		if err := rows.Scan(&i.ItemID, &i.AcquiredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
