// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: table_bets.sql

package store

import (
	"context"
)

const insertTableBet = `-- name: InsertTableBet :one
INSERT INTO bets (user_id, game_id, round_id, bet_credits, payout_credits, action)
VALUES ($1, $2, $3, $4, $5, 'play')
RETURNING id
`

type InsertTableBetParams struct {
	UserID        int64
	GameID        string
	RoundID       int64
	BetCredits    int64
	PayoutCredits int64
}

// One bets row per player per poker hand: bet = matched contribution,
// payout = chips won from the pots. Wallet money only moves on buy-in and
// cash-out (stacks are house-held), so this row is the hand's record.
func (q *Queries) InsertTableBet(ctx context.Context, arg InsertTableBetParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTableBet,
		arg.UserID,
		arg.GameID,
		arg.RoundID,
		arg.BetCredits,
		arg.PayoutCredits,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
