// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: themes.sql

package store

import (
	"context"
	"time"
)

const createTheme = `-- name: CreateTheme :one
INSERT INTO themes (user_id, name, palette, sprites, prompt_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, palette, sprites, prompt_hash, created_at
`

type CreateThemeParams struct {
	UserID     int64
	Name       string
	Palette    []byte
	Sprites    []byte
	PromptHash string
}

type CreateThemeRow struct {
	ID         int64
	UserID     int64
	Name       string
	Palette    []byte
	Sprites    []byte
	PromptHash string
	CreatedAt  time.Time
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) (CreateThemeRow, error) {
	row := q.db.QueryRow(ctx, createTheme,
		arg.UserID,
		arg.Name,
		arg.Palette,
		arg.Sprites,
		arg.PromptHash,
	)
	var i CreateThemeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Palette,
		&i.Sprites,
		&i.PromptHash,
		&i.CreatedAt,
	)
	return i, err
}

const getThemeByPromptHash = `-- name: GetThemeByPromptHash :one
SELECT id, user_id, name, palette, sprites, prompt_hash, created_at
FROM themes
WHERE user_id = $1 AND prompt_hash = $2
ORDER BY id DESC
LIMIT 1
`

type GetThemeByPromptHashParams struct {
	UserID     int64
	PromptHash string
}

type GetThemeByPromptHashRow struct {
	ID         int64
	UserID     int64
	Name       string
	Palette    []byte
	Sprites    []byte
	PromptHash string
	CreatedAt  time.Time
}

func (q *Queries) GetThemeByPromptHash(ctx context.Context, arg GetThemeByPromptHashParams) (GetThemeByPromptHashRow, error) {
	row := q.db.QueryRow(ctx, getThemeByPromptHash, arg.UserID, arg.PromptHash)
	var i GetThemeByPromptHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Palette,
		&i.Sprites,
		&i.PromptHash,
		&i.CreatedAt,
	)
	return i, err
}

const listThemesByUser = `-- name: ListThemesByUser :many
SELECT id, user_id, name, palette, sprites, prompt_hash, created_at
FROM themes
WHERE user_id = $1
ORDER BY id DESC
LIMIT 50
`

type ListThemesByUserRow struct {
	ID         int64
	UserID     int64
	Name       string
	Palette    []byte
	Sprites    []byte
	PromptHash string
	CreatedAt  time.Time
}

func (q *Queries) ListThemesByUser(ctx context.Context, userID int64) ([]ListThemesByUserRow, error) {
	rows, err := q.db.Query(ctx, listThemesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThemesByUserRow
	for rows.Next() {
		var i ListThemesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Palette,
			&i.Sprites,
			&i.PromptHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
