// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminListUsers = `-- name: AdminListUsers :many
SELECT id, created_at, is_guest, display_name, email, email_verified_at,
       role, status, status_until
FROM users
WHERE $1::text = ''
   OR display_name ILIKE '%' || $1::text || '%'
   OR email::text ILIKE '%' || $1::text || '%'
ORDER BY id DESC
LIMIT $2
`

type AdminListUsersParams struct {
	Term    string
	MaxRows int32
}

type AdminListUsersRow struct {
	ID              int64
	CreatedAt       time.Time
	IsGuest         bool
	DisplayName     string
	Email           *string
	EmailVerifiedAt *time.Time
	Role            string
	Status          string
	StatusUntil     *time.Time
}

// Search by display name or email substring; empty term lists newest first.
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers, arg.Term, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListUsersRow
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.IsGuest,
			&i.DisplayName,
			&i.Email,
			&i.EmailVerifiedAt,
			&i.Role,
			&i.Status,
			&i.StatusUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearAvatar = `-- name: ClearAvatar :execrows
UPDATE users
SET avatar_preset = NULL, avatar_version = avatar_version + 1
WHERE id = $1
`

func (q *Queries) ClearAvatar(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, clearAvatar, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUserGuest = `-- name: CreateUserGuest :one
INSERT INTO users (display_name, is_guest)
VALUES ($1, true)
RETURNING id, created_at, is_guest, display_name, email, password_hash,
          email_verified_at, role, status, status_until,
          avatar_preset, avatar_version, display_name_updated_at
`

func (q *Queries) CreateUserGuest(ctx context.Context, displayName string) (User, error) {
	row := q.db.QueryRow(ctx, createUserGuest, displayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.IsGuest,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.Status,
		&i.StatusUntil,
		&i.AvatarPreset,
		&i.AvatarVersion,
		&i.DisplayNameUpdatedAt,
	)
	return i, err
}

const createUserRegistered = `-- name: CreateUserRegistered :one
INSERT INTO users (display_name, email, password_hash, is_guest)
VALUES ($1, $2, $3, false)
RETURNING id, created_at, is_guest, display_name, email, password_hash,
          email_verified_at, role, status, status_until,
          avatar_preset, avatar_version, display_name_updated_at
`

type CreateUserRegisteredParams struct {
	DisplayName  string
	Email        *string
	PasswordHash pgtype.Text
}

func (q *Queries) CreateUserRegistered(ctx context.Context, arg CreateUserRegisteredParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserRegistered, arg.DisplayName, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.IsGuest,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.Status,
		&i.StatusUntil,
		&i.AvatarPreset,
		&i.AvatarVersion,
		&i.DisplayNameUpdatedAt,
	)
	return i, err
}

const displayNameTaken = `-- name: DisplayNameTaken :one
SELECT count(*) > 0 AS taken
FROM users
WHERE lower(display_name) = lower($1) AND id <> $2
`

type DisplayNameTakenParams struct {
	Lower string
	ID    int64
}

// Case-insensitive uniqueness check; ownership excluded by caller id.
func (q *Queries) DisplayNameTaken(ctx context.Context, arg DisplayNameTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, displayNameTaken, arg.Lower, arg.ID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, is_guest, display_name, email, password_hash,
       email_verified_at, role, status, status_until,
       avatar_preset, avatar_version, display_name_updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.IsGuest,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.Status,
		&i.StatusUntil,
		&i.AvatarPreset,
		&i.AvatarVersion,
		&i.DisplayNameUpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, is_guest, display_name, email, password_hash,
       email_verified_at, role, status, status_until,
       avatar_preset, avatar_version, display_name_updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.IsGuest,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.Status,
		&i.StatusUntil,
		&i.AvatarPreset,
		&i.AvatarVersion,
		&i.DisplayNameUpdatedAt,
	)
	return i, err
}

const getUserPublicProfile = `-- name: GetUserPublicProfile :one
SELECT id, display_name, avatar_preset, avatar_version, role, created_at
FROM users
WHERE id = $1
`

type GetUserPublicProfileRow struct {
	ID            int64
	DisplayName   string
	AvatarPreset  pgtype.Text
	AvatarVersion int64
	Role          string
	CreatedAt     time.Time
}

func (q *Queries) GetUserPublicProfile(ctx context.Context, id int64) (GetUserPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserPublicProfile, id)
	var i GetUserPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarPreset,
		&i.AvatarVersion,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const setAvatarPreset = `-- name: SetAvatarPreset :execrows
UPDATE users
SET avatar_preset = $2, avatar_version = avatar_version + 1
WHERE id = $1
`

type SetAvatarPresetParams struct {
	ID           int64
	AvatarPreset pgtype.Text
}

func (q *Queries) SetAvatarPreset(ctx context.Context, arg SetAvatarPresetParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAvatarPreset, arg.ID, arg.AvatarPreset)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUploadedAvatar = `-- name: SetUploadedAvatar :one
UPDATE users
SET avatar_preset = NULL, avatar_version = avatar_version + 1
WHERE id = $1
RETURNING avatar_version
`

// An upload clears any preset; the version bump moves the public URL.
func (q *Queries) SetUploadedAvatar(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, setUploadedAvatar, id)
	var avatar_version int64
	err := row.Scan(&avatar_version)
	return avatar_version, err
}

const updateDisplayName = `-- name: UpdateDisplayName :one
UPDATE users
SET display_name = $2, display_name_updated_at = now()
WHERE id = $1
RETURNING id, created_at, is_guest, display_name, email, password_hash,
          email_verified_at, role, status, status_until,
          avatar_preset, avatar_version, display_name_updated_at
`

type UpdateDisplayNameParams struct {
	ID          int64
	DisplayName string
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.IsGuest,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.Status,
		&i.StatusUntil,
		&i.AvatarPreset,
		&i.AvatarVersion,
		&i.DisplayNameUpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           int64
	PasswordHash pgtype.Text
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE users SET email_verified_at = now() WHERE id = $1
`

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, id)
	return err
}

const upgradeGuestUser = `-- name: UpgradeGuestUser :one
UPDATE users
SET email = $2, password_hash = $3, is_guest = false
WHERE id = $1 AND is_guest = true
RETURNING id, created_at, is_guest, display_name, email, password_hash,
          email_verified_at, role, status, status_until,
          avatar_preset, avatar_version, display_name_updated_at
`

type UpgradeGuestUserParams struct {
	ID           int64
	Email        *string
	PasswordHash pgtype.Text
}

// Guest upgrade in place: the same row keeps its wallet, bets, and seeds.
func (q *Queries) UpgradeGuestUser(ctx context.Context, arg UpgradeGuestUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upgradeGuestUser, arg.ID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.IsGuest,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.Status,
		&i.StatusUntil,
		&i.AvatarPreset,
		&i.AvatarVersion,
		&i.DisplayNameUpdatedAt,
	)
	return i, err
}
