// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const createUserGuest = `-- name: CreateUserGuest :one
INSERT INTO users (display_name, is_guest)
VALUES ($1, true)
RETURNING id, created_at, is_guest, display_name, email, password_hash,
          email_verified_at, role, status, status_until
`

func (q *Queries) CreateUserGuest(ctx context.Context, displayName string) (User, error) {
	row := q.db.QueryRow(ctx, createUserGuest, displayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.IsGuest,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.Status,
		&i.StatusUntil,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, is_guest, display_name, email, password_hash,
       email_verified_at, role, status, status_until
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.IsGuest,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.Status,
		&i.StatusUntil,
	)
	return i, err
}
