// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :exec
INSERT INTO wallets (user_id, balance_credits)
VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
`

type CreateWalletParams struct {
	UserID         int64
	BalanceCredits int64
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) error {
	_, err := q.db.Exec(ctx, createWallet, arg.UserID, arg.BalanceCredits)
	return err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, wallet_id, kind, amount_credits, bet_id, idempotency_key, created_at
FROM transactions
WHERE idempotency_key = $1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Kind,
		&i.AmountCredits,
		&i.BetID,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletBalance = `-- name: GetWalletBalance :one
SELECT balance_credits FROM wallets WHERE user_id = $1
`

func (q *Queries) GetWalletBalance(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getWalletBalance, userID)
	var balance_credits int64
	err := row.Scan(&balance_credits)
	return balance_credits, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (wallet_id, kind, amount_credits, bet_id, idempotency_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type InsertTransactionParams struct {
	WalletID       int64
	Kind           string
	AmountCredits  int64
	BetID          pgtype.Int8
	IdempotencyKey string
}

type InsertTransactionRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (InsertTransactionRow, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.WalletID,
		arg.Kind,
		arg.AmountCredits,
		arg.BetID,
		arg.IdempotencyKey,
	)
	var i InsertTransactionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const lockWalletForUpdate = `-- name: LockWalletForUpdate :one
SELECT user_id, balance_credits FROM wallets WHERE user_id = $1 FOR UPDATE
`

// The play/settlement path must always take this row lock before reading or
// writing a balance. Two simultaneous bets on one wallet serialize here.
func (q *Queries) LockWalletForUpdate(ctx context.Context, userID int64) (Wallet, error) {
	row := q.db.QueryRow(ctx, lockWalletForUpdate, userID)
	var i Wallet
	err := row.Scan(&i.UserID, &i.BalanceCredits)
	return i, err
}

const lockWalletsSorted = `-- name: LockWalletsSorted :many
SELECT user_id, balance_credits FROM wallets
WHERE user_id = ANY($1::bigint[])
ORDER BY user_id
FOR UPDATE
`

// Multi-wallet settlement locks rows in ascending user_id order to make
// deadlocks impossible. Callers pass an unordered set; SQL orders.
func (q *Queries) LockWalletsSorted(ctx context.Context, dollar_1 []int64) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, lockWalletsSorted, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(&i.UserID, &i.BalanceCredits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTransactions = `-- name: SumTransactions :one
SELECT COALESCE(SUM(amount_credits), 0)::bigint AS total
FROM transactions
WHERE wallet_id = $1
`

func (q *Queries) SumTransactions(ctx context.Context, walletID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumTransactions, walletID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :one
UPDATE wallets
SET balance_credits = balance_credits + $2
WHERE user_id = $1
RETURNING balance_credits
`

type UpdateWalletBalanceParams struct {
	UserID         int64
	BalanceCredits int64
}

// The cached materialization is updated in the same transaction as the
// ledger insert. Nothing may write it without a matching transaction row.
func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateWalletBalance, arg.UserID, arg.BalanceCredits)
	var balance_credits int64
	err := row.Scan(&balance_credits)
	return balance_credits, err
}
